import type { MicroHeroPreset } from "@/lib/toolbox-slug-themes";

export type ToolboxRendererKind = "native" | "composed_v1" | "external_link";
export type ToolboxContentTypeStatus =
  | "draft"
  | "pending_review"
  | "published"
  | "deprecated";

export interface ToolboxContentTypeDefinition {
  slug: string;
  label_fr: string;
  label_en: string;
  description_fr: string;
  description_en: string;
  category: string;
  icon: string;
  renderer_kind: ToolboxRendererKind;
  status: ToolboxContentTypeStatus;
  config_schema: Record<string, unknown>;
  ui_blueprint: Record<string, unknown>;
  sample_config: Record<string, unknown>;
  default_title_fr: string;
  default_title_en: string;
}

const composed = (
  slug: string,
  labelFr: string,
  labelEn: string,
  category: string,
  icon: string,
  descriptionFr: string,
  descriptionEn: string,
  sampleConfig: Record<string, unknown>,
  required: string[] = [],
  blocks: string[] = ["markdown", "step_list", "timer"],
): ToolboxContentTypeDefinition => ({
  slug,
  label_fr: labelFr,
  label_en: labelEn,
  description_fr: descriptionFr,
  description_en: descriptionEn,
  category,
  icon,
  renderer_kind: "composed_v1",
  status: "published",
  config_schema: { type: "object", required },
  ui_blueprint: { blocks },
  sample_config: sampleConfig,
  default_title_fr: labelFr,
  default_title_en: labelEn,
});

const nativeExercise = (
  slug: string,
  labelFr: string,
  labelEn: string,
  category: string,
  icon: string,
  descriptionFr: string,
  descriptionEn: string,
  sampleConfig: Record<string, unknown>,
  required: string[] = ["instructions"],
  presentation: string,
  theme?: { accent: string; hero?: MicroHeroPreset },
): ToolboxContentTypeDefinition => ({
  slug,
  label_fr: labelFr,
  label_en: labelEn,
  description_fr: descriptionFr,
  description_en: descriptionEn,
  category,
  icon,
  renderer_kind: "native",
  status: "published",
  config_schema: { type: "object", required },
  ui_blueprint: { presentation, theme },
  sample_config: {
    ...sampleConfig,
    ...(theme?.accent ? { accent_color: theme.accent } : {}),
    ...(theme?.hero ? { hero: theme.hero } : {}),
  },
  default_title_fr: labelFr,
  default_title_en: labelEn,
});

export const BUILTIN_TOOLBOX_CONTENT_TYPES: ToolboxContentTypeDefinition[] = [
  {
    slug: "breathwork",
    label_fr: "Respiration guidée",
    label_en: "Guided breathwork",
    description_fr: "Cycles inspirer / pause / expirer.",
    description_en: "Inhale / hold / exhale cycles.",
    category: "regulation",
    icon: "wind",
    renderer_kind: "native",
    status: "published",
    config_schema: {
      type: "object",
      required: [
        "cycles",
        "breath_in_sec",
        "pause1_sec",
        "breath_out_sec",
        "pause2_sec",
      ],
    },
    ui_blueprint: { blocks: ["native"] },
    sample_config: {
      cycles: 4,
      breath_in_sec: 4,
      pause1_sec: 4,
      breath_out_sec: 6,
      pause2_sec: 2,
    },
    default_title_fr: "Respiration 4-4-6-2",
    default_title_en: "Breathwork 4-4-6-2",
  },
  {
    slug: "focus_introspectif",
    label_fr: "Focus introspectif",
    label_en: "Introspective focus",
    description_fr: "Focalisation guidée sur une intention.",
    description_en: "Guided focus on a chosen intention.",
    category: "attention",
    icon: "eye",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object", required: ["duration_min", "intention"] },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { duration_min: 12, intention: "Rester centré(e) malgré le bruit" },
    default_title_fr: "Focus introspectif",
    default_title_en: "Introspective focus",
  },
  {
    slug: "body_scan",
    label_fr: "Body scan",
    label_en: "Body scan",
    description_fr: "Parcours des zones corporelles.",
    description_en: "Sequential body-area awareness scan.",
    category: "body",
    icon: "scan",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object" },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { duration_min: 10, zones: ["head", "shoulders", "chest", "abdomen", "legs", "feet"] },
    default_title_fr: "Scan corporel complet",
    default_title_en: "Full body scan",
  },
  {
    slug: "visualization",
    label_fr: "Visualisation",
    label_en: "Visualization",
    description_fr: "Visualisation guidée en scènes.",
    description_en: "Scene-based guided visualization.",
    category: "attention",
    icon: "sparkles",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object" },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { total_sec: 480, scenes: [{ title: "Ancrage", sec: 120 }, { title: "Projection", sec: 180 }] },
    default_title_fr: "Visualisation de réussite",
    default_title_en: "Success visualization",
  },
  {
    slug: "affirmations",
    label_fr: "Affirmations",
    label_en: "Affirmations",
    description_fr: "Affirmations positives chronométrées.",
    description_en: "Timed positive affirmation loop.",
    category: "cognitive",
    icon: "stars",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object", required: ["duration_min", "affirmations"] },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { duration_min: 5, affirmations: ["Je suis capable", "Je reste stable"] },
    default_title_fr: "Affirmations du matin",
    default_title_en: "Morning affirmations",
  },
  {
    slug: "gratitude",
    label_fr: "Gratitude",
    label_en: "Gratitude",
    description_fr: "Exercice de gratitude guidé.",
    description_en: "Guided gratitude entry exercise.",
    category: "journal",
    icon: "heart",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object", required: ["entries_count"] },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { entries_count: 3 },
    default_title_fr: "3 gratitudes",
    default_title_en: "3 gratitudes",
  },
  {
    slug: "journal_prompt",
    label_fr: "Prompt journal",
    label_en: "Journal prompt",
    description_fr: "Question guidée d’introspection.",
    description_en: "Prompted introspection question.",
    category: "journal",
    icon: "book",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object", required: ["prompt"] },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { prompt: "Qu’est-ce qui m’a le plus surpris aujourd’hui ?" },
    default_title_fr: "Prompt journal du jour",
    default_title_en: "Today journal prompt",
  },
  {
    slug: "stop_protocol",
    label_fr: "Protocole STOP",
    label_en: "STOP protocol",
    description_fr: "S-T-O-P pour régulation rapide.",
    description_en: "S-T-O-P sequence for quick regulation.",
    category: "regulation",
    icon: "shield",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object" },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { mode: "timed", step_duration_sec: 45 },
    default_title_fr: "STOP rapide",
    default_title_en: "Quick STOP",
  },
  {
    slug: "intention",
    label_fr: "Intention",
    label_en: "Intention",
    description_fr: "Intention consciente de la journée.",
    description_en: "Conscious daily intention exercise.",
    category: "intentionality",
    icon: "target",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object" },
    ui_blueprint: { blocks: ["native"] },
    sample_config: { intention: "Agir avec calme et clarté", duration_min: 6 },
    default_title_fr: "Intention du jour",
    default_title_en: "Daily intention",
  },
  {
    slug: "micro_practice",
    label_fr: "Micro-pratique",
    label_en: "Micro practice",
    description_fr: "Bloc flexible pour exercices custom.",
    description_en: "Flexible renderer for custom exercises.",
    category: "custom",
    icon: "zap",
    renderer_kind: "native",
    status: "published",
    config_schema: { type: "object", required: ["instructions"] },
    ui_blueprint: { blocks: ["native"] },
    sample_config: {
      instructions: "3 séries de 10 squats lents avec respiration nasale.",
      duration_sec: 300,
      steps: [{ text: "Échauffement 30 sec" }, { text: "3 x 10 squats" }],
    },
    default_title_fr: "Activation matinale",
    default_title_en: "Morning activation",
  },
  {
    slug: "breath_box",
    label_fr: "Respiration Box",
    label_en: "Box breathing",
    description_fr: "Respiration carrée 4-4-4-4.",
    description_en: "Square breathing 4-4-4-4.",
    category: "regulation",
    icon: "wind",
    renderer_kind: "native",
    status: "published",
    config_schema: {
      type: "object",
      required: [
        "cycles",
        "breath_in_sec",
        "pause1_sec",
        "breath_out_sec",
        "pause2_sec",
      ],
    },
    ui_blueprint: { blocks: ["native"] },
    sample_config: {
      cycles: 15,
      breath_in_sec: 4,
      pause1_sec: 4,
      breath_out_sec: 4,
      pause2_sec: 4,
      breath_visual: "box",
      instructions:
        "4 sec inspire, 4 sec pause, 4 sec expire, 4 sec pause — suis le point sur le carré.",
    },
    default_title_fr: "Respiration Box",
    default_title_en: "Box breathing",
  },
  {
    slug: "breath_coherence",
    label_fr: "Cohérence cardiaque",
    label_en: "Cardiac coherence",
    description_fr: "Cohérence respiratoire 5/5.",
    description_en: "5/5 coherence breathing.",
    category: "regulation",
    icon: "wind",
    renderer_kind: "native",
    status: "published",
    config_schema: {
      type: "object",
      required: [
        "cycles",
        "breath_in_sec",
        "pause1_sec",
        "breath_out_sec",
        "pause2_sec",
      ],
    },
    ui_blueprint: { blocks: ["native"] },
    sample_config: {
      cycles: 30,
      breath_in_sec: 5,
      pause1_sec: 0,
      breath_out_sec: 5,
      pause2_sec: 0,
      breath_visual: "circle",
      instructions: "Inspire 5 sec / Expire 5 sec, en continu.",
    },
    default_title_fr: "Cohérence cardiaque",
    default_title_en: "Cardiac coherence",
  },
  nativeExercise(
    "physiological_sigh",
    "Soupir physiologique",
    "Physiological sigh",
    "regulation",
    "wind",
    "Deux inspirations suivies d’une longue expiration.",
    "Two inhales then long exhale.",
    {
      cycles: 8,
      breath_in_sec: 2,
      pause1_sec: 1,
      breath_out_sec: 8,
      pause2_sec: 0,
      instructions: "Fais 8 répétitions lentes : double inspiration, longue expiration.",
    },
    ["instructions"],
    "breathwork",
    { accent: "hsl(176 70% 48%)" },
  ),
  nativeExercise(
    "vagal_hum",
    "Humming vagal",
    "Vagal humming",
    "regulation",
    "wind",
    "Vibration vocale guidée.",
    "Guided humming for vagal tone.",
    {
      cycles: 15,
      breath_in_sec: 4,
      pause1_sec: 0,
      breath_out_sec: 8,
      pause2_sec: 0,
      instructions: "Hum doucement sur chaque expiration.",
    },
    ["instructions"],
    "breathwork",
    { accent: "hsl(200 70% 55%)" },
  ),
  nativeExercise(
    "micro_movement",
    "Micro-mouvement",
    "Micro movement",
    "body",
    "zap",
    "Micro séquence mouvement.",
    "Micro movement sequence.",
    {
      instructions: "3 séries de 10 squats.",
      steps: [{ text: "Set 1" }, { text: "Set 2" }, { text: "Set 3" }],
      duration_sec: 300,
    },
    ["instructions"],
    "micro",
    { accent: "hsl(35 80% 58%)", hero: "pulse" },
  ),
  nativeExercise(
    "shake_release",
    "Shake release",
    "Shake release",
    "body",
    "zap",
    "Décharge somatique par secousses.",
    "Somatic shake release.",
    { instructions: "Secoue bras et jambes 90 sec.", duration_sec: 90 },
    ["instructions"],
    "micro",
    { accent: "hsl(0 65% 55%)", hero: "shake" },
  ),
  nativeExercise(
    "progressive_relax",
    "Relaxation progressive",
    "Progressive relaxation",
    "body",
    "scan",
    "Contracte puis relâche groupes musculaires.",
    "Contract then release muscle groups.",
    {
      instructions: "Parcours chaque groupe : contracte 5 sec, relâche 10 sec.",
      steps: [{ text: "Mains" }, { text: "Épaules" }, { text: "Jambes" }],
    },
    ["instructions"],
    "body_scan",
    { accent: "hsl(176 70% 48%)" },
  ),
  nativeExercise(
    "walking_meditation",
    "Marche consciente",
    "Walking meditation",
    "body",
    "footprints",
    "Marche lente et attentive.",
    "Slow mindful walking.",
    { instructions: "10 minutes en conscience des pas.", duration_sec: 600 },
    ["instructions"],
    "micro",
    { accent: "hsl(160 50% 45%)", hero: "steps" },
  ),
  nativeExercise(
    "cold_exposure_prep",
    "Préparation froid",
    "Cold exposure prep",
    "body",
    "snowflake",
    "Routine sécurité avant exposition au froid.",
    "Safety routine before cold exposure.",
    {
      instructions: "Respire, posture, entrée progressive.",
      steps: [{ text: "Respiration" }, { text: "Entrée progressive" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(200 70% 55%)", hero: "orbit" },
  ),
  nativeExercise(
    "posture_reset",
    "Reset posture",
    "Posture reset",
    "body",
    "align-center",
    "Réinitialisation posturale.",
    "Posture reset flow.",
    {
      instructions: "3 alignements sur 2 minutes.",
      steps: [{ text: "Nuque" }, { text: "Épaules" }, { text: "Bassin" }],
      duration_sec: 120,
    },
    ["instructions"],
    "micro",
    { accent: "hsl(176 70% 48%)", hero: "steps" },
  ),
  nativeExercise(
    "energy_activation",
    "Activation énergétique",
    "Energy activation",
    "body",
    "activity",
    "Activation du corps en début de journée.",
    "Morning body activation.",
    {
      instructions: "Séquence de 5 min.",
      steps: [{ text: "Respire" }, { text: "Mobilise" }, { text: "Ancre" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(45 90% 55%)", hero: "flame" },
  ),
  nativeExercise(
    "safe_place",
    "Lieu refuge",
    "Safe place",
    "attention",
    "mountain",
    "Visualisation d’un lieu refuge.",
    "Safe-place visualization.",
    { instructions: "Construis un lieu sûr sensoriel.", duration_sec: 420 },
    ["instructions"],
    "visualization",
    { accent: "hsl(220 70% 60%)" },
  ),
  nativeExercise(
    "open_monitoring",
    "Observation ouverte",
    "Open monitoring",
    "attention",
    "eye",
    "Observer pensées/sensations sans jugement.",
    "Observe thoughts and sensations openly.",
    { instructions: "Assieds-toi et observe 8 min.", duration_sec: 480 },
    ["instructions"],
    "visualization",
    { accent: "hsl(270 50% 60%)" },
  ),
  nativeExercise(
    "journal_stream",
    "Écriture libre",
    "Journal stream",
    "journal",
    "pen-line",
    "Écriture spontanée continue.",
    "Continuous free writing.",
    { instructions: "Écris sans t’arrêter 10 min.", duration_sec: 600 },
    ["instructions"],
    "journal_timed",
    { accent: "hsl(220 70% 60%)", hero: "ink" },
  ),
  nativeExercise(
    "gratitude_triple",
    "Gratitude x3",
    "Gratitude x3",
    "journal",
    "heart",
    "Trois points de gratitude.",
    "Three gratitude entries.",
    { instructions: "Note 3 gratitudes concrètes.", entries_count: 3 },
    ["instructions"],
    "gratitude",
  ),
  nativeExercise(
    "worry_dump",
    "Worry dump",
    "Worry dump",
    "journal",
    "cloud-rain",
    "Décharger les préoccupations puis prioriser.",
    "Dump worries then prioritize.",
    {
      instructions: "Liste tes inquiétudes, puis classe-les.",
      steps: [{ text: "Liste brute" }, { text: "Classement" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(220 55% 55%)", hero: "ink" },
  ),
  nativeExercise(
    "letter_unsent",
    "Lettre non envoyée",
    "Unsent letter",
    "journal",
    "mail",
    "Lettre émotionnelle sans envoi.",
    "Emotional letter never sent.",
    { instructions: "Écris une lettre brute en 12 min.", duration_sec: 720 },
    ["instructions"],
    "journal_timed",
    { accent: "hsl(0 55% 55%)", hero: "ink" },
  ),
  nativeExercise(
    "dialogue_parts",
    "Dialogue des parts",
    "Parts dialogue",
    "journal",
    "messages-square",
    "Dialogue entre deux voix internes.",
    "Dialogue between two inner voices.",
    { instructions: "Alterne Voix A et Voix B.", fields: ["Voix A", "Voix B"] },
    ["instructions"],
    "dialogue_parts",
    { accent: "hsl(220 70% 60%)" },
  ),
  nativeExercise(
    "evening_review",
    "Revue du soir",
    "Evening review",
    "journal",
    "moon",
    "Bilan de fin de journée.",
    "End-of-day review.",
    {
      instructions: "Ce que j’ai fait / ressenti / appris.",
      steps: [{ text: "Faits" }, { text: "Ressenti" }, { text: "Demain" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(250 45% 55%)", hero: "ink" },
  ),
  nativeExercise(
    "morning_pages",
    "Morning pages",
    "Morning pages",
    "journal",
    "notebook-pen",
    "Pages du matin sans filtre.",
    "Morning pages practice.",
    { instructions: "Écris librement 3 pages ou 15 min.", duration_sec: 900 },
    ["instructions"],
    "journal_timed",
    { accent: "hsl(45 70% 55%)", hero: "ink" },
  ),
  nativeExercise(
    "intention_morning",
    "Intention matin",
    "Morning intention",
    "intentionality",
    "sunrise",
    "Définir l’intention principale du matin.",
    "Define your core morning intention.",
    { instructions: "Formule ton intention du jour.", fields: ["Intention"] },
    ["instructions"],
    "intention",
    { accent: "hsl(45 90% 55%)" },
  ),
  nativeExercise(
    "intention_week",
    "Intention semaine",
    "Weekly intention",
    "intentionality",
    "calendar-days",
    "Intention hebdomadaire et 3 actions.",
    "Weekly intention and 3 actions.",
    {
      instructions: "Une intention, trois actions.",
      fields: ["Intention", "Action 1", "Action 2", "Action 3"],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(270 50% 60%)", hero: "steps" },
  ),
  nativeExercise(
    "ritual_sequence",
    "Séquence rituelle",
    "Ritual sequence",
    "intentionality",
    "list-checks",
    "Rituel structuré en étapes.",
    "Structured ritual in steps.",
    {
      instructions: "Coche chaque étape du rituel.",
      steps: [{ text: "Hydratation" }, { text: "Respiration" }, { text: "Focus" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(270 50% 60%)", hero: "steps" },
  ),
  nativeExercise(
    "habit_checkbox",
    "Habitude simple",
    "Simple habit",
    "intentionality",
    "check-square",
    "Une habitude à cocher.",
    "Single checkbox habit.",
    {
      instructions: "As-tu réalisé cette habitude ?",
      habit_name: "10 squats matin",
      steps: [{ text: "10 squats matin" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(176 70% 48%)", hero: "pulse" },
  ),
  nativeExercise(
    "affirmations_cycle",
    "Cycle d’affirmations",
    "Affirmations cycle",
    "cognitive",
    "stars",
    "Cycle guidé d’affirmations.",
    "Guided affirmations cycle.",
    {
      instructions: "Répète chaque phrase à voix calme.",
      duration_min: 5,
      affirmations: ["Je reste stable", "Je passe à l’action"],
    },
    ["instructions", "duration_min", "affirmations"],
    "affirmations",
  ),
  nativeExercise(
    "belief_reframe",
    "Reframe croyance",
    "Belief reframe",
    "cognitive",
    "brain",
    "Transformer une croyance limitante.",
    "Reframe a limiting belief.",
    {
      instructions: "Croyance → preuve contraire → nouvelle croyance.",
      steps: [{ text: "Croyance" }, { text: "Preuve contraire" }, { text: "Reframe" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(270 50% 60%)", hero: "spark" },
  ),
  nativeExercise(
    "if_then_plan",
    "Plan if/then",
    "If/then plan",
    "cognitive",
    "git-branch-plus",
    "Plan d’implémentation comportemental.",
    "Implementation intention planning.",
    {
      instructions: "Si X alors je fais Y.",
      steps: [{ text: "Déclencheur" }, { text: "Action" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(176 70% 48%)", hero: "steps" },
  ),
  nativeExercise(
    "decision_matrix",
    "Matrice de décision",
    "Decision matrix",
    "cognitive",
    "table",
    "Comparer options et critères.",
    "Compare options and criteria.",
    {
      instructions: "Évalue 2 options sur ton critère principal.",
      fields: ["Option A", "Option B", "Critère principal"],
    },
    ["instructions"],
    "decision_matrix",
    { accent: "hsl(35 80% 58%)" },
  ),
  nativeExercise(
    "stop_rumination",
    "Stop rumination",
    "Stop rumination",
    "cognitive",
    "circle-stop",
    "Interrompre boucle de rumination.",
    "Interrupt rumination loop.",
    {
      instructions: "Nommer boucle, respirer, rediriger.",
      duration_sec: 180,
      steps: [{ text: "Nommer la boucle" }, { text: "Respirer" }, { text: "Rediriger" }],
    },
    ["instructions"],
    "stop_protocol",
  ),
  nativeExercise(
    "archetype_mirror",
    "Miroir archétype",
    "Archetype mirror",
    "myss",
    "sparkles",
    "Questionner l’archétype dominant du moment.",
    "Question the currently dominant archetype.",
    {
      instructions: "Observe ton archétype en action.",
      steps: [{ text: "Archétype" }, { text: "Signal" }, { text: "Action" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(35 80% 58%)", hero: "spark" },
  ),
  nativeExercise(
    "shadow_checkin",
    "Check-in ombre",
    "Shadow check-in",
    "myss",
    "moon-star",
    "Mesurer l’intensité d’une ombre active.",
    "Assess active shadow intensity.",
    {
      instructions: "Score 0-10 + déclencheur.",
      fields: ["Ombre", "Intensité", "Déclencheur"],
    },
    ["instructions"],
    "shadow_checkin",
    { accent: "hsl(270 40% 45%)" },
  ),
  nativeExercise(
    "light_quality_practice",
    "Pratique lumière",
    "Light quality practice",
    "myss",
    "sun",
    "Activer une qualité lumière concrète.",
    "Activate a concrete light quality.",
    {
      instructions: "Choisis une qualité et un geste concret.",
      steps: [{ text: "Qualité" }, { text: "Action" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(45 90% 55%)", hero: "flame" },
  ),
  nativeExercise(
    "symbol_encounter",
    "Rencontre symbole",
    "Symbol encounter",
    "myss",
    "gem",
    "Noter un symbole marquant et son sens.",
    "Capture a symbolic moment and meaning.",
    {
      instructions: "Quel symbole ? Quel sens ? Quelle action ?",
      steps: [{ text: "Symbole" }, { text: "Sens" }, { text: "Action" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(270 50% 60%)", hero: "spark" },
  ),
  nativeExercise(
    "boundary_practice",
    "Pratique des limites",
    "Boundary practice",
    "myss",
    "shield",
    "Exercer un non clair et aligné.",
    "Practice clear and aligned boundaries.",
    {
      instructions: "Prépare ta phrase de limite.",
      steps: [{ text: "Situation" }, { text: "Phrase de limite" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(0 65% 55%)", hero: "shield" },
  ),
  nativeExercise(
    "sacred_no",
    "Non sacré",
    "Sacred no",
    "myss",
    "shield-ban",
    "Dire non sans culpabilité.",
    "Say no without guilt.",
    {
      instructions: "Formule ton non + alternative éventuelle.",
      steps: [{ text: "Non" }, { text: "Alternative" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(220 70% 60%)", hero: "shield" },
  ),
  nativeExercise(
    "energy_ledger",
    "Bilan énergétique",
    "Energy ledger",
    "myss",
    "battery",
    "Ce qui nourrit / vide l’énergie.",
    "What nourishes vs drains energy.",
    {
      instructions: "Liste les gains et pertes d’énergie.",
      steps: [{ text: "Nourrit" }, { text: "Draine" }, { text: "Ajustement" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(176 70% 48%)", hero: "orbit" },
  ),
  nativeExercise(
    "synchronicity_log",
    "Log synchronicité",
    "Synchronicity log",
    "myss",
    "sparkles",
    "Tracer les synchronicités et signaux.",
    "Track synchronicities and signals.",
    {
      instructions: "Événement, ressenti, lecture.",
      steps: [{ text: "Événement" }, { text: "Ressenti" }, { text: "Hypothèse" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(270 50% 60%)", hero: "spark" },
  ),
  nativeExercise(
    "relation_repair",
    "Réparation relation",
    "Relationship repair",
    "relations",
    "users",
    "Structurer une réparation relationnelle.",
    "Structure relational repair.",
    {
      instructions: "Reconnaître, réparer, proposer.",
      steps: [{ text: "Fait" }, { text: "Impact" }, { text: "Demande" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(200 70% 55%)", hero: "steps" },
  ),
  nativeExercise(
    "empathy_perspective",
    "Perspective empathique",
    "Empathy perspective",
    "relations",
    "users-round",
    "Prendre perspective moi/autre/pont.",
    "Take self/other/bridge perspective.",
    {
      instructions: "Remplis les trois colonnes.",
      fields: ["Moi", "Autre", "Pont"],
    },
    ["instructions"],
    "empathy_perspective",
    { accent: "hsl(176 70% 48%)" },
  ),
  nativeExercise(
    "social_micro_action",
    "Micro-action sociale",
    "Social micro action",
    "relations",
    "handshake",
    "Une micro-action relationnelle immédiate.",
    "One immediate social micro-action.",
    {
      instructions: "Choisis une action sociale réalisable aujourd’hui.",
      steps: [{ text: "Action" }, { text: "Quand" }],
    },
    ["instructions"],
    "micro",
    { accent: "hsl(176 70% 48%)", hero: "pulse" },
  ),
];

export const BUILTIN_TOOLBOX_CONTENT_TYPE_MAP = new Map(
  BUILTIN_TOOLBOX_CONTENT_TYPES.map((def) => [def.slug, def]),
);

export function getBuiltinToolboxContentTypeDefinition(
  slug: string,
): ToolboxContentTypeDefinition | null {
  return BUILTIN_TOOLBOX_CONTENT_TYPE_MAP.get(slug) ?? null;
}

export function mergeContentTypeDefinitions(
  overrides: Array<Partial<ToolboxContentTypeDefinition> & { slug: string }>,
): ToolboxContentTypeDefinition[] {
  const bySlug = new Map(
    BUILTIN_TOOLBOX_CONTENT_TYPES.map((def) => [def.slug, { ...def }]),
  );
  for (const override of overrides) {
    const base = bySlug.get(override.slug);
    if (base) {
      bySlug.set(override.slug, { ...base, ...override });
    } else {
      bySlug.set(override.slug, {
        slug: override.slug,
        label_fr: override.label_fr ?? override.slug,
        label_en: override.label_en ?? override.slug,
        description_fr: override.description_fr ?? "",
        description_en: override.description_en ?? "",
        category: override.category ?? "custom",
        icon: override.icon ?? "zap",
        renderer_kind: override.renderer_kind ?? "composed_v1",
        status: override.status ?? "draft",
        config_schema: override.config_schema ?? { type: "object" },
        ui_blueprint: override.ui_blueprint ?? { blocks: ["markdown"] },
        sample_config: override.sample_config ?? {},
        default_title_fr: override.default_title_fr ?? override.label_fr ?? override.slug,
        default_title_en: override.default_title_en ?? override.label_en ?? override.slug,
      });
    }
  }
  return Array.from(bySlug.values());
}
