project_id = "wjjugtdciljmuohxoqcj"

[functions.drive-debug]
verify_jwt = true

[functions.send-newsletter-email]
verify_jwt = false

[functions.scan-alerts]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = false
