import type { ArchetypeDef, ArchetypeKey } from "./types";

/**
 * The 12 universal archetypes (Caroline Myss). Single source of truth.
 * Keys MUST match the BDD (assessment_options.archetype_weights, archetype_scores.archetype_key).
 * Colors use HSL strings to stay aligned with the design system.
 */
export const ARCHETYPES: ArchetypeDef[] = [
  {
    key: "sage",
    family: "wisdom",
    name_fr: "Le Sage",
    name_en: "The Sage",
    shortDescription_fr: "Cherche la vérité, comprend en profondeur, transmet la clarté.",
    shortDescription_en: "Seeks truth, understands deeply, transmits clarity.",
    lightAspect_fr: "Discernement, lucidité, capacité de synthèse.",
    lightAspect_en: "Discernment, lucidity, ability to synthesize.",
    shadowAspect_fr: "Sur-mentalisation, distance émotionnelle, dogmatisme.",
    shadowAspect_en: "Over-thinking, emotional distance, dogmatism.",
    coreNeed_fr: "Comprendre et transmettre le vrai.",
    coreNeed_en: "Understand and transmit truth.",
    fearPattern_fr: "Peur de l'ignorance et de l'erreur.",
    fearPattern_en: "Fear of ignorance and error.",
    color: "hsl(220 70% 65%)",
  },
  {
    key: "warrior",
    family: "action",
    name_fr: "Le Guerrier",
    name_en: "The Warrior",
    shortDescription_fr: "Agit, protège, tient bon dans l'adversité.",
    shortDescription_en: "Acts, protects, holds firm in adversity.",
    lightAspect_fr: "Courage, discipline, force d'exécution.",
    lightAspect_en: "Courage, discipline, executional strength.",
    shadowAspect_fr: "Agressivité, surmenage, déni des limites.",
    shadowAspect_en: "Aggression, burnout, denial of limits.",
    coreNeed_fr: "Se battre pour ce qui compte.",
    coreNeed_en: "Fight for what matters.",
    fearPattern_fr: "Peur de la faiblesse et de l'échec.",
    fearPattern_en: "Fear of weakness and failure.",
    color: "hsl(0 75% 60%)",
  },
  {
    key: "lover",
    family: "relation",
    name_fr: "L'Amoureux",
    name_en: "The Lover",
    shortDescription_fr: "Crée du lien, célèbre la beauté de la relation.",
    shortDescription_en: "Creates connection, celebrates the beauty of relation.",
    lightAspect_fr: "Présence, sensualité, capacité à relier.",
    lightAspect_en: "Presence, sensuality, ability to connect.",
    shadowAspect_fr: "Dépendance affective, fusion, perte de soi dans l'autre.",
    shadowAspect_en: "Emotional dependency, fusion, loss of self in the other.",
    coreNeed_fr: "Aimer et être en lien.",
    coreNeed_en: "Love and be in relation.",
    fearPattern_fr: "Peur de l'abandon et de la solitude.",
    fearPattern_en: "Fear of abandonment and loneliness.",
    color: "hsl(330 70% 65%)",
  },
  {
    key: "sovereign",
    family: "leadership",
    name_fr: "Le Souverain",
    name_en: "The Sovereign",
    shortDescription_fr: "Incarne l'autorité juste et structure le collectif.",
    shortDescription_en: "Embodies fair authority and structures the collective.",
    lightAspect_fr: "Vision, décision, stature et clarté.",
    lightAspect_en: "Vision, decisiveness, stature and clarity.",
    shadowAspect_fr: "Contrôle, isolement, dureté.",
    shadowAspect_en: "Control, isolation, harshness.",
    coreNeed_fr: "Régner avec justesse et impact.",
    coreNeed_en: "Reign with rightness and impact.",
    fearPattern_fr: "Peur de l'impuissance et du désordre.",
    fearPattern_en: "Fear of powerlessness and chaos.",
    color: "hsl(45 90% 60%)",
  },
  {
    key: "magician",
    family: "transformation",
    name_fr: "Le Magicien",
    name_en: "The Magician",
    shortDescription_fr: "Transforme l'invisible en réel, ouvre des possibles.",
    shortDescription_en: "Transforms the invisible into real, opens possibilities.",
    lightAspect_fr: "Vision stratégique, intuition, capacité de transformation.",
    lightAspect_en: "Strategic vision, intuition, transformative capacity.",
    shadowAspect_fr: "Manipulation, élitisme, détachement du concret.",
    shadowAspect_en: "Manipulation, elitism, detachment from the concrete.",
    coreNeed_fr: "Faire advenir ce qui n'existe pas encore.",
    coreNeed_en: "Bring forth what does not yet exist.",
    fearPattern_fr: "Peur de la stagnation et de l'impuissance créatrice.",
    fearPattern_en: "Fear of stagnation and creative powerlessness.",
    color: "hsl(190 75% 55%)",
  },
  {
    key: "healer",
    family: "transformation",
    name_fr: "Le Guérisseur",
    name_en: "The Healer",
    shortDescription_fr: "Restaure ce qui est blessé chez soi et chez les autres.",
    shortDescription_en: "Restores what is wounded in self and others.",
    lightAspect_fr: "Compassion lucide, présence thérapeutique, intégration.",
    lightAspect_en: "Lucid compassion, therapeutic presence, integration.",
    shadowAspect_fr: "Surcharge émotionnelle, identification aux blessures, sauveur.",
    shadowAspect_en: "Emotional overload, wound identification, savior pattern.",
    coreNeed_fr: "Réparer et intégrer.",
    coreNeed_en: "Repair and integrate.",
    fearPattern_fr: "Peur de la souffrance non vue.",
    fearPattern_en: "Fear of unseen suffering.",
    color: "hsl(135 50% 55%)",
  },
  {
    key: "creator",
    family: "expression",
    name_fr: "Le Créateur",
    name_en: "The Creator",
    shortDescription_fr: "Donne forme à l'invisible et célèbre la beauté.",
    shortDescription_en: "Gives form to the invisible and celebrates beauty.",
    lightAspect_fr: "Imagination, sensibilité, expression authentique.",
    lightAspect_en: "Imagination, sensitivity, authentic expression.",
    shadowAspect_fr: "Procrastination, instabilité émotionnelle, blocage créatif.",
    shadowAspect_en: "Procrastination, emotional instability, creative block.",
    coreNeed_fr: "Créer et exprimer librement.",
    coreNeed_en: "Create and express freely.",
    fearPattern_fr: "Peur de la médiocrité et de la censure.",
    fearPattern_en: "Fear of mediocrity and censorship.",
    color: "hsl(290 70% 65%)",
  },
  {
    key: "rebel",
    family: "action",
    name_fr: "Le Rebelle",
    name_en: "The Rebel",
    shortDescription_fr: "Bouscule l'ordre établi pour libérer le neuf.",
    shortDescription_en: "Disrupts the established order to free the new.",
    lightAspect_fr: "Audace, lucidité, capacité à dire non.",
    lightAspect_en: "Boldness, lucidity, ability to say no.",
    shadowAspect_fr: "Opposition systématique, isolement, autodestruction.",
    shadowAspect_en: "Systematic opposition, isolation, self-destruction.",
    coreNeed_fr: "Se libérer des contraintes injustes.",
    coreNeed_en: "Free oneself from unjust constraints.",
    fearPattern_fr: "Peur d'être contrôlé ou réduit au silence.",
    fearPattern_en: "Fear of being controlled or silenced.",
    color: "hsl(15 80% 60%)",
  },
  {
    key: "caregiver",
    family: "relation",
    name_fr: "Le Soignant",
    name_en: "The Caregiver",
    shortDescription_fr: "Prend soin, soutient, fait grandir l'autre.",
    shortDescription_en: "Cares, supports, grows others.",
    lightAspect_fr: "Empathie, présence, générosité.",
    lightAspect_en: "Empathy, presence, generosity.",
    shadowAspect_fr: "Sacrifice de soi, dépendance affective, sauvetage.",
    shadowAspect_en: "Self-sacrifice, emotional dependency, rescuing.",
    coreNeed_fr: "Se sentir utile aux autres.",
    coreNeed_en: "Feel useful to others.",
    fearPattern_fr: "Peur d'être égoïste ou abandonné.",
    fearPattern_en: "Fear of being selfish or abandoned.",
    color: "hsl(150 55% 55%)",
  },
  {
    key: "explorer",
    family: "wisdom",
    name_fr: "L'Explorateur",
    name_en: "The Explorer",
    shortDescription_fr: "Apprend en continu, traverse les territoires inconnus.",
    shortDescription_en: "Learns continuously, crosses unknown territories.",
    lightAspect_fr: "Curiosité, plasticité, courage d'apprendre.",
    lightAspect_en: "Curiosity, plasticity, courage to learn.",
    shadowAspect_fr: "Dispersion, fuite en avant, accumulation sans action.",
    shadowAspect_en: "Dispersion, forward flight, accumulation without action.",
    coreNeed_fr: "Découvrir et progresser.",
    coreNeed_en: "Discover and progress.",
    fearPattern_fr: "Peur d'être enfermé ou de stagner.",
    fearPattern_en: "Fear of being locked-in or stagnating.",
    color: "hsl(180 60% 55%)",
  },
  {
    key: "mystic",
    family: "wisdom",
    name_fr: "Le Mystique",
    name_en: "The Mystic",
    shortDescription_fr: "Quête du sacré, du sens et de l'unité.",
    shortDescription_en: "Quest for the sacred, meaning and unity.",
    lightAspect_fr: "Intériorité, intuition, ouverture transcendante.",
    lightAspect_en: "Inwardness, intuition, transcendent openness.",
    shadowAspect_fr: "Fuite du réel, spiritual bypassing, dispersion.",
    shadowAspect_en: "Reality avoidance, spiritual bypassing, dispersion.",
    coreNeed_fr: "Se relier à plus grand que soi.",
    coreNeed_en: "Connect to something greater than self.",
    fearPattern_fr: "Peur du vide et de la séparation.",
    fearPattern_en: "Fear of emptiness and separation.",
    color: "hsl(260 65% 70%)",
  },
  {
    key: "jester",
    family: "expression",
    name_fr: "Le Bouffon",
    name_en: "The Jester",
    shortDescription_fr: "Transforme le sérieux en jeu, révèle les vérités cachées.",
    shortDescription_en: "Turns the serious into play, reveals hidden truths.",
    lightAspect_fr: "Légèreté, vivacité, lucidité ironique.",
    lightAspect_en: "Lightness, vivacity, ironic lucidity.",
    shadowAspect_fr: "Évitement par l'humour, cynisme, fuite du sérieux nécessaire.",
    shadowAspect_en: "Humor avoidance, cynicism, fleeing necessary seriousness.",
    coreNeed_fr: "Vivre pleinement l'instant.",
    coreNeed_en: "Live fully in the moment.",
    fearPattern_fr: "Peur de l'ennui et de la lourdeur.",
    fearPattern_en: "Fear of boredom and heaviness.",
    color: "hsl(48 95% 60%)",
  },
];

export const ARCHETYPE_KEYS: ArchetypeKey[] = ARCHETYPES.map((a) => a.key);

export function getArchetype(key: ArchetypeKey): ArchetypeDef {
  const a = ARCHETYPES.find((x) => x.key === key);
  if (!a) throw new Error(`Unknown archetype: ${key}`);
  return a;
}
