import type { ArchetypeDef, ArchetypeKey } from "./types";

/**
 * The 12 archetypes (Caroline Myss inspired). Single source of truth.
 * Colors use the existing design system palette (HSL semantic tokens).
 */
export const ARCHETYPES: ArchetypeDef[] = [
  {
    key: "advocate",
    family: "guardian",
    name_fr: "L'Avocat",
    name_en: "The Advocate",
    shortDescription_fr: "Défend les causes justes et donne la parole aux invisibles.",
    shortDescription_en: "Stands for just causes and gives voice to the unseen.",
    lightAspect_fr: "Courage moral, persévérance, sens aigu de la justice.",
    lightAspect_en: "Moral courage, perseverance, sharp sense of justice.",
    shadowAspect_fr: "Combat permanent, dureté envers soi, manichéisme.",
    shadowAspect_en: "Constant fight, harshness toward self, black-and-white thinking.",
    coreNeed_fr: "Servir une cause plus grande que soi.",
    coreNeed_en: "Serve a cause greater than self.",
    fearPattern_fr: "Peur de l'injustice et de l'impuissance.",
    fearPattern_en: "Fear of injustice and powerlessness.",
    color: "hsl(210 80% 60%)",
  },
  {
    key: "artist",
    family: "creator",
    name_fr: "L'Artiste",
    name_en: "The Artist",
    shortDescription_fr: "Donne forme à l'invisible et célèbre la beauté.",
    shortDescription_en: "Gives form to the invisible and celebrates beauty.",
    lightAspect_fr: "Imagination, sensibilité, expression authentique.",
    lightAspect_en: "Imagination, sensitivity, authentic expression.",
    shadowAspect_fr: "Procrastination, instabilité émotionnelle, blocage créatif.",
    shadowAspect_en: "Procrastination, emotional instability, creative block.",
    coreNeed_fr: "Créer et exprimer librement.",
    coreNeed_en: "Create and express freely.",
    fearPattern_fr: "Peur de la médiocrité et de la censure.",
    fearPattern_en: "Fear of mediocrity and censorship.",
    color: "hsl(290 70% 65%)",
  },
  {
    key: "athlete",
    family: "warrior",
    name_fr: "L'Athlète",
    name_en: "The Athlete",
    shortDescription_fr: "Discipline et performance au service de l'excellence corporelle.",
    shortDescription_en: "Discipline and performance in service of bodily excellence.",
    lightAspect_fr: "Endurance, focus, force mentale.",
    lightAspect_en: "Endurance, focus, mental strength.",
    shadowAspect_fr: "Surmenage, identification au résultat, déni des limites.",
    shadowAspect_en: "Burnout, results-identification, denial of limits.",
    coreNeed_fr: "Se dépasser physiquement et mentalement.",
    coreNeed_en: "Push physical and mental limits.",
    fearPattern_fr: "Peur de la faiblesse et de l'échec.",
    fearPattern_en: "Fear of weakness and failure.",
    color: "hsl(0 75% 60%)",
  },
  {
    key: "caregiver",
    family: "nurturer",
    name_fr: "Le Soignant",
    name_en: "The Caregiver",
    shortDescription_fr: "Prend soin, soutient, fait grandir l'autre.",
    shortDescription_en: "Cares, supports, grows others.",
    lightAspect_fr: "Empathie, présence, générosité.",
    lightAspect_en: "Empathy, presence, generosity.",
    shadowAspect_fr: "Sacrifice de soi, dépendance affective, sauvetage.",
    shadowAspect_en: "Self-sacrifice, emotional dependency, rescuing.",
    coreNeed_fr: "Se sentir utile aux autres.",
    coreNeed_en: "Feel useful to others.",
    fearPattern_fr: "Peur d'être égoïste ou abandonné.",
    fearPattern_en: "Fear of being selfish or abandoned.",
    color: "hsl(150 55% 55%)",
  },
  {
    key: "intellectual",
    family: "thinker",
    name_fr: "L'Intellectuel",
    name_en: "The Intellectual",
    shortDescription_fr: "Comprend, analyse, structure le réel par la pensée.",
    shortDescription_en: "Understands, analyzes, structures reality through thought.",
    lightAspect_fr: "Clarté, rigueur, capacité de synthèse.",
    lightAspect_en: "Clarity, rigor, synthesis.",
    shadowAspect_fr: "Sur-mentalisation, déconnexion du corps, paralysie d'analyse.",
    shadowAspect_en: "Over-thinking, disconnection from body, analysis paralysis.",
    coreNeed_fr: "Comprendre et donner du sens.",
    coreNeed_en: "Understand and make meaning.",
    fearPattern_fr: "Peur de l'ignorance et du non-sens.",
    fearPattern_en: "Fear of ignorance and meaninglessness.",
    color: "hsl(220 70% 65%)",
  },
  {
    key: "queen",
    family: "leader",
    name_fr: "La Reine / L'Exécutif",
    name_en: "The Queen / Executive",
    shortDescription_fr: "Incarne l'autorité juste et structure le collectif.",
    shortDescription_en: "Embodies fair authority and structures the collective.",
    lightAspect_fr: "Vision, décision, stature et clarté.",
    lightAspect_en: "Vision, decisiveness, stature and clarity.",
    shadowAspect_fr: "Contrôle, isolement, dureté.",
    shadowAspect_en: "Control, isolation, harshness.",
    coreNeed_fr: "Régner avec justesse et impact.",
    coreNeed_en: "Lead with rightness and impact.",
    fearPattern_fr: "Peur de l'impuissance et du désordre.",
    fearPattern_en: "Fear of powerlessness and chaos.",
    color: "hsl(45 90% 60%)",
  },
  {
    key: "rebel",
    family: "disruptor",
    name_fr: "Le Rebelle",
    name_en: "The Rebel",
    shortDescription_fr: "Bouscule l'ordre établi pour libérer le neuf.",
    shortDescription_en: "Disrupts the established order to free the new.",
    lightAspect_fr: "Audace, lucidité, capacité à dire non.",
    lightAspect_en: "Boldness, lucidity, ability to say no.",
    shadowAspect_fr: "Opposition systématique, isolement, autodestruction.",
    shadowAspect_en: "Systematic opposition, isolation, self-destruction.",
    coreNeed_fr: "Se libérer des contraintes injustes.",
    coreNeed_en: "Free oneself from unjust constraints.",
    fearPattern_fr: "Peur d'être contrôlé ou réduit au silence.",
    fearPattern_en: "Fear of being controlled or silenced.",
    color: "hsl(15 80% 60%)",
  },
  {
    key: "spiritual_seeker",
    family: "seeker",
    name_fr: "Le Chercheur Spirituel",
    name_en: "The Spiritual Seeker",
    shortDescription_fr: "Quête du sens, du sacré et de l'unité.",
    shortDescription_en: "Quest for meaning, sacred and unity.",
    lightAspect_fr: "Intériorité, intuition, ouverture transcendante.",
    lightAspect_en: "Inwardness, intuition, transcendent openness.",
    shadowAspect_fr: "Fuite du réel, spiritual bypassing, dispersion.",
    shadowAspect_en: "Reality avoidance, spiritual bypassing, dispersion.",
    coreNeed_fr: "Se relier à plus grand que soi.",
    coreNeed_en: "Connect to something greater than self.",
    fearPattern_fr: "Peur du vide et de la séparation.",
    fearPattern_en: "Fear of emptiness and separation.",
    color: "hsl(260 65% 70%)",
  },
  {
    key: "visionary",
    family: "innovator",
    name_fr: "Le Visionnaire",
    name_en: "The Visionary",
    shortDescription_fr: "Voit l'avenir et trace de nouveaux chemins.",
    shortDescription_en: "Sees the future and charts new paths.",
    lightAspect_fr: "Imagination stratégique, anticipation, inspiration.",
    lightAspect_en: "Strategic imagination, anticipation, inspiration.",
    shadowAspect_fr: "Détachement du concret, frustration, élitisme.",
    shadowAspect_en: "Detachment from the concrete, frustration, elitism.",
    coreNeed_fr: "Donner forme à un futur désirable.",
    coreNeed_en: "Shape a desirable future.",
    fearPattern_fr: "Peur de la stagnation.",
    fearPattern_en: "Fear of stagnation.",
    color: "hsl(190 75% 55%)",
  },
  {
    key: "student",
    family: "learner",
    name_fr: "L'Étudiant",
    name_en: "The Student",
    shortDescription_fr: "Apprend en continu et grandit par la curiosité.",
    shortDescription_en: "Learns continuously and grows through curiosity.",
    lightAspect_fr: "Humilité, curiosité, plasticité mentale.",
    lightAspect_en: "Humility, curiosity, mental plasticity.",
    shadowAspect_fr: "Procrastination intellectuelle, doute chronique, accumulation sans action.",
    shadowAspect_en: "Intellectual procrastination, chronic doubt, accumulating without acting.",
    coreNeed_fr: "Apprendre et progresser.",
    coreNeed_en: "Learn and progress.",
    fearPattern_fr: "Peur de ne pas savoir assez.",
    fearPattern_en: "Fear of not knowing enough.",
    color: "hsl(180 60% 55%)",
  },
  {
    key: "healer",
    family: "restorer",
    name_fr: "Le Guérisseur",
    name_en: "The Healer",
    shortDescription_fr: "Restaure ce qui est blessé chez soi et chez les autres.",
    shortDescription_en: "Restores what is wounded in self and others.",
    lightAspect_fr: "Compassion lucide, présence thérapeutique, intégration.",
    lightAspect_en: "Lucid compassion, therapeutic presence, integration.",
    shadowAspect_fr: "Surcharge émotionnelle, identification aux blessures, sauveur.",
    shadowAspect_en: "Emotional overload, wound identification, savior pattern.",
    coreNeed_fr: "Réparer et intégrer.",
    coreNeed_en: "Repair and integrate.",
    fearPattern_fr: "Peur de la souffrance non vue.",
    fearPattern_en: "Fear of unseen suffering.",
    color: "hsl(135 50% 55%)",
  },
  {
    key: "networker",
    family: "connector",
    name_fr: "Le Connecteur",
    name_en: "The Networker",
    shortDescription_fr: "Crée des ponts entre les personnes et les idées.",
    shortDescription_en: "Builds bridges between people and ideas.",
    lightAspect_fr: "Sociabilité, fluidité, sens de l'opportunité.",
    lightAspect_en: "Sociability, fluidity, sense of opportunity.",
    shadowAspect_fr: "Superficialité, instrumentalisation, dispersion.",
    shadowAspect_en: "Superficiality, instrumentalization, dispersion.",
    coreNeed_fr: "Relier et activer.",
    coreNeed_en: "Connect and activate.",
    fearPattern_fr: "Peur de l'isolement et de l'invisibilité.",
    fearPattern_en: "Fear of isolation and invisibility.",
    color: "hsl(330 70% 65%)",
  },
];

export const ARCHETYPE_KEYS: ArchetypeKey[] = ARCHETYPES.map((a) => a.key);

export function getArchetype(key: ArchetypeKey): ArchetypeDef {
  const a = ARCHETYPES.find((x) => x.key === key);
  if (!a) throw new Error(`Unknown archetype: ${key}`);
  return a;
}
