import type { QuestionSeed } from "./types";

/**
 * 30 questions covering the 12 archetypes and 7 dimensions.
 * Mix of single_choice (archetype scoring), likert_scale (dimensions/shadow),
 * multiple_choice, ranking and short_text.
 */
export const QUESTIONS: QuestionSeed[] = [
  // ---- Single choice (archetype) ----
  {
    position: 1,
    type: "single_choice",
    prompt_fr: "Quand un projet démarre, qu'est-ce qui vous vient en premier ?",
    prompt_en: "When a project starts, what comes to you first?",
    options: [
      { position: 1, label_fr: "La vision globale et le futur souhaité", label_en: "The big picture and the desired future", archetypeWeights: { visionary: 3, queen: 1 } },
      { position: 2, label_fr: "Les détails à comprendre et structurer", label_en: "The details to understand and structure", archetypeWeights: { intellectual: 3, student: 1 } },
      { position: 3, label_fr: "Les personnes à embarquer", label_en: "The people to bring along", archetypeWeights: { networker: 2, caregiver: 2 } },
      { position: 4, label_fr: "L'action concrète à lancer maintenant", label_en: "The concrete action to launch now", archetypeWeights: { athlete: 2, rebel: 2 } },
    ],
  },
  {
    position: 2,
    type: "single_choice",
    prompt_fr: "Face à une injustice, votre réflexe est de…",
    prompt_en: "Facing an injustice, your reflex is to…",
    options: [
      { position: 1, label_fr: "Prendre la parole publiquement", archetypeWeights: { advocate: 3, rebel: 1 }, label_en: "Speak up publicly" },
      { position: 2, label_fr: "Soigner ceux qui sont touchés", archetypeWeights: { caregiver: 2, healer: 2 }, label_en: "Care for those impacted" },
      { position: 3, label_fr: "Analyser le système pour le réformer", archetypeWeights: { intellectual: 2, queen: 2 }, label_en: "Analyze the system to reform it" },
      { position: 4, label_fr: "Créer une œuvre qui en témoigne", archetypeWeights: { artist: 3 }, label_en: "Create a work that bears witness" },
    ],
  },
  {
    position: 3,
    type: "single_choice",
    prompt_fr: "Votre énergie déborde quand vous…",
    prompt_en: "Your energy overflows when you…",
    options: [
      { position: 1, label_fr: "Dépassez une limite physique", archetypeWeights: { athlete: 3 }, label_en: "Push past a physical limit" },
      { position: 2, label_fr: "Connectez deux personnes brillantes", archetypeWeights: { networker: 3 }, label_en: "Connect two brilliant people" },
      { position: 3, label_fr: "Apprenez quelque chose de neuf", archetypeWeights: { student: 3, intellectual: 1 }, label_en: "Learn something new" },
      { position: 4, label_fr: "Touchez le sacré ou l'invisible", archetypeWeights: { spiritual_seeker: 3 }, label_en: "Touch the sacred or invisible" },
    ],
  },
  {
    position: 4,
    type: "single_choice",
    prompt_fr: "On vous reconnaît surtout pour…",
    prompt_en: "You are mostly recognized for…",
    options: [
      { position: 1, label_fr: "Votre clarté et votre autorité", archetypeWeights: { queen: 3 }, label_en: "Your clarity and authority" },
      { position: 2, label_fr: "Votre capacité à réparer / soigner", archetypeWeights: { healer: 3, caregiver: 1 }, label_en: "Your ability to repair / care" },
      { position: 3, label_fr: "Votre regard décalé / disruptif", archetypeWeights: { rebel: 3, artist: 1 }, label_en: "Your disruptive perspective" },
      { position: 4, label_fr: "Votre vision long terme", archetypeWeights: { visionary: 3 }, label_en: "Your long-term vision" },
    ],
  },
  {
    position: 5,
    type: "single_choice",
    prompt_fr: "Quand vous êtes au mieux, vous…",
    prompt_en: "At your best, you…",
    options: [
      { position: 1, label_fr: "Décidez vite et juste", archetypeWeights: { queen: 2, athlete: 1 }, label_en: "Decide fast and right" },
      { position: 2, label_fr: "Créez quelque chose de neuf", archetypeWeights: { artist: 2, visionary: 1 }, label_en: "Create something new" },
      { position: 3, label_fr: "Soutenez quelqu'un en croissance", archetypeWeights: { caregiver: 2, healer: 1 }, label_en: "Support someone growing" },
      { position: 4, label_fr: "Comprenez ce que d'autres ne voient pas", archetypeWeights: { intellectual: 2, spiritual_seeker: 1 }, label_en: "See what others miss" },
    ],
  },
  {
    position: 6,
    type: "single_choice",
    prompt_fr: "Sous stress, vous avez tendance à…",
    prompt_en: "Under stress you tend to…",
    options: [
      { position: 1, label_fr: "Prendre le contrôle de tout", archetypeWeights: { queen: 1, athlete: 1 }, shadowWeights: { control: 2 }, label_en: "Take control of everything" },
      { position: 2, label_fr: "Vous retirer / disparaître", archetypeWeights: { spiritual_seeker: 1 }, shadowWeights: { withdrawal: 2 }, label_en: "Withdraw / disappear" },
      { position: 3, label_fr: "Dire oui à trop de choses", archetypeWeights: { caregiver: 1 }, shadowWeights: { people_pleasing: 2 }, label_en: "Say yes to too much" },
      { position: 4, label_fr: "Repousser la décision", archetypeWeights: { student: 1, intellectual: 1 }, shadowWeights: { avoidance: 2, self_doubt: 1 }, label_en: "Postpone the decision" },
    ],
  },
  {
    position: 7,
    type: "single_choice",
    prompt_fr: "Votre plus grande peur est de…",
    prompt_en: "Your deepest fear is to…",
    options: [
      { position: 1, label_fr: "Ne pas avoir d'impact", archetypeWeights: { queen: 2, advocate: 1 }, shadowWeights: { control: 1 }, label_en: "Have no impact" },
      { position: 2, label_fr: "Être abandonné·e", archetypeWeights: { caregiver: 2 }, shadowWeights: { people_pleasing: 1 }, label_en: "Be abandoned" },
      { position: 3, label_fr: "Être réduit·e au silence", archetypeWeights: { rebel: 2, advocate: 1 }, label_en: "Be silenced" },
      { position: 4, label_fr: "Ne pas comprendre", archetypeWeights: { intellectual: 2, student: 1 }, shadowWeights: { self_doubt: 1 }, label_en: "Not understand" },
    ],
  },
  {
    position: 8,
    type: "single_choice",
    prompt_fr: "Vous apprenez le mieux par…",
    prompt_en: "You learn best by…",
    dimension: "learning_style",
    options: [
      { position: 1, label_fr: "L'expérimentation directe", archetypeWeights: { athlete: 1, rebel: 1 }, value: 0.9, label_en: "Direct experimentation" },
      { position: 2, label_fr: "La lecture et la théorie", archetypeWeights: { intellectual: 2, student: 1 }, value: 0.7, label_en: "Reading and theory" },
      { position: 3, label_fr: "L'échange avec un mentor", archetypeWeights: { student: 2, networker: 1 }, value: 0.6, label_en: "Exchange with a mentor" },
      { position: 4, label_fr: "L'introspection silencieuse", archetypeWeights: { spiritual_seeker: 2 }, value: 0.8, label_en: "Silent introspection" },
    ],
  },

  // ---- Multiple choice ----
  {
    position: 9,
    type: "multiple_choice",
    prompt_fr: "Quels environnements vous nourrissent ? (jusqu'à 3)",
    prompt_en: "Which environments feed you? (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "La nature silencieuse", archetypeWeights: { spiritual_seeker: 2, healer: 1 }, label_en: "Silent nature" },
      { position: 2, label_fr: "Les espaces de création", archetypeWeights: { artist: 2 }, label_en: "Creative spaces" },
      { position: 3, label_fr: "Les salles de décision", archetypeWeights: { queen: 2, advocate: 1 }, label_en: "Decision rooms" },
      { position: 4, label_fr: "Les terrains d'effort physique", archetypeWeights: { athlete: 2 }, label_en: "Physical training grounds" },
      { position: 5, label_fr: "Les communautés vibrantes", archetypeWeights: { networker: 2, caregiver: 1 }, label_en: "Vibrant communities" },
      { position: 6, label_fr: "Les bibliothèques", archetypeWeights: { intellectual: 2, student: 1 }, label_en: "Libraries" },
    ],
  },
  {
    position: 10,
    type: "multiple_choice",
    prompt_fr: "Qu'est-ce qui vous fait perdre votre énergie ? (jusqu'à 3)",
    prompt_en: "What drains your energy? (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Les conflits non résolus", shadowWeights: { withdrawal: 1 }, archetypeWeights: { caregiver: 1 }, label_en: "Unresolved conflicts" },
      { position: 2, label_fr: "Les réunions sans décision", shadowWeights: { control: 1 }, archetypeWeights: { queen: 1 }, label_en: "Meetings without a decision" },
      { position: 3, label_fr: "Le bruit social superficiel", shadowWeights: { withdrawal: 1 }, archetypeWeights: { intellectual: 1, spiritual_seeker: 1 }, label_en: "Superficial social noise" },
      { position: 4, label_fr: "Les règles arbitraires", shadowWeights: { control: 1 }, archetypeWeights: { rebel: 2 }, label_en: "Arbitrary rules" },
      { position: 5, label_fr: "Devoir dire non", shadowWeights: { people_pleasing: 2 }, archetypeWeights: { caregiver: 1 }, label_en: "Having to say no" },
      { position: 6, label_fr: "Devoir performer", shadowWeights: { perfectionism: 2 }, archetypeWeights: { athlete: 1 }, label_en: "Having to perform" },
    ],
  },

  // ---- Likert (dimensions / shadow) ----
  {
    position: 11,
    type: "likert_scale",
    prompt_fr: "Je préfère apprendre seul·e plutôt qu'en groupe.",
    prompt_en: "I prefer learning alone rather than in a group.",
    dimension: "learning_style",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 12,
    type: "likert_scale",
    prompt_fr: "Mes meilleures décisions émergent dans la relation.",
    prompt_en: "My best decisions emerge in relationship.",
    dimension: "relational_style",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 13,
    type: "likert_scale",
    prompt_fr: "J'ai besoin d'intensité pour me sentir vivant·e.",
    prompt_en: "I need intensity to feel alive.",
    dimension: "activation_style",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 14,
    type: "likert_scale",
    prompt_fr: "Je sais redescendre rapidement après un pic de stress.",
    prompt_en: "I can come down quickly after a stress peak.",
    dimension: "regulation_need",
    helper_fr: "Réponse inversée : un score bas signifie un fort besoin de régulation.",
    helper_en: "Reverse-scored: a low answer means a high regulation need.",
    meta: { min: 1, max: 7, reverse: true },
    options: [
      { position: 1, value: 1, label_fr: "1", label_en: "1" },
      { position: 2, value: 6 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 5 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 3 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 2 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1 / 7, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 15,
    type: "likert_scale",
    prompt_fr: "Je fais confiance à mes intuitions, même sans preuve.",
    prompt_en: "I trust my intuitions even without proof.",
    dimension: "self_trust",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 16,
    type: "likert_scale",
    prompt_fr: "J'ai besoin d'exprimer ce que je vis, sinon je m'éteins.",
    prompt_en: "I need to express what I live, otherwise I dim.",
    dimension: "expression_need",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 17,
    type: "likert_scale",
    prompt_fr: "J'ai besoin d'un cadre clair pour donner le meilleur.",
    prompt_en: "I need a clear frame to give my best.",
    dimension: "structure_need",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 18,
    type: "likert_scale",
    prompt_fr: "J'ai du mal à déléguer ce qui compte vraiment.",
    prompt_en: "I struggle to delegate what really matters.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { control: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { control: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { control: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { control: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { control: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { control: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { control: 3, perfectionism: 1 }, label_en: "7" },
    ],
  },
  {
    position: 19,
    type: "likert_scale",
    prompt_fr: "Je dis oui même quand mon corps dit non.",
    prompt_en: "I say yes even when my body says no.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { people_pleasing: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { people_pleasing: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { people_pleasing: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { people_pleasing: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { people_pleasing: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { people_pleasing: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { people_pleasing: 3 }, label_en: "7" },
    ],
  },
  {
    position: 20,
    type: "likert_scale",
    prompt_fr: "Quand c'est trop, je disparais socialement.",
    prompt_en: "When it's too much, I disappear socially.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { withdrawal: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { withdrawal: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { withdrawal: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { withdrawal: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { withdrawal: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { withdrawal: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { withdrawal: 3 }, label_en: "7" },
    ],
  },
  {
    position: 21,
    type: "likert_scale",
    prompt_fr: "Je doute de mes décisions même quand elles sont bonnes.",
    prompt_en: "I doubt my decisions even when they are good.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { self_doubt: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { self_doubt: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { self_doubt: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { self_doubt: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { self_doubt: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { self_doubt: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { self_doubt: 3 }, label_en: "7" },
    ],
  },
  {
    position: 22,
    type: "likert_scale",
    prompt_fr: "Tant que ce n'est pas parfait, je ne livre pas.",
    prompt_en: "Until it's perfect, I don't ship.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { perfectionism: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { perfectionism: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { perfectionism: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { perfectionism: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { perfectionism: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { perfectionism: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { perfectionism: 3 }, label_en: "7" },
    ],
  },
  {
    position: 23,
    type: "likert_scale",
    prompt_fr: "Je remets à plus tard ce qui me fait peur.",
    prompt_en: "I postpone what scares me.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { avoidance: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { avoidance: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { avoidance: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { avoidance: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { avoidance: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { avoidance: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { avoidance: 3 }, label_en: "7" },
    ],
  },

  // ---- Single choice (more archetype coverage) ----
  {
    position: 24,
    type: "single_choice",
    prompt_fr: "Le matin, ce qui vous met en route, c'est…",
    prompt_en: "In the morning, what gets you going is…",
    options: [
      { position: 1, label_fr: "Une intention claire", archetypeWeights: { visionary: 2, queen: 1 }, label_en: "A clear intention" },
      { position: 2, label_fr: "Un rituel corporel", archetypeWeights: { athlete: 2, healer: 1 }, label_en: "A bodily ritual" },
      { position: 3, label_fr: "Une question ouverte", archetypeWeights: { intellectual: 2, student: 2 }, label_en: "An open question" },
      { position: 4, label_fr: "Un moment de silence", archetypeWeights: { spiritual_seeker: 2 }, label_en: "A moment of silence" },
    ],
  },
  {
    position: 25,
    type: "single_choice",
    prompt_fr: "Quand vous coachez quelqu'un, votre force est…",
    prompt_en: "When you coach someone, your strength is…",
    options: [
      { position: 1, label_fr: "Voir leur potentiel inexploré", archetypeWeights: { visionary: 2, healer: 1 }, label_en: "See their untapped potential" },
      { position: 2, label_fr: "Structurer un plan d'action", archetypeWeights: { queen: 2, intellectual: 1 }, label_en: "Structure an action plan" },
      { position: 3, label_fr: "Créer un espace sûr", archetypeWeights: { caregiver: 2, healer: 2 }, label_en: "Create a safe space" },
      { position: 4, label_fr: "Les confronter avec amour", archetypeWeights: { rebel: 2, advocate: 1 }, label_en: "Confront them with love" },
    ],
  },

  // ---- Ranking ----
  {
    position: 26,
    type: "ranking",
    prompt_fr: "Classez ces moteurs internes du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these inner drivers from strongest (1) to weakest (4).",
    helper_fr: "Glissez pour réordonner.",
    helper_en: "Drag to reorder.",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Impact", label_en: "Impact", archetypeWeights: { queen: 2, advocate: 1 } },
      { position: 2, label_fr: "Liberté", label_en: "Freedom", archetypeWeights: { rebel: 2, artist: 1 } },
      { position: 3, label_fr: "Lien", label_en: "Connection", archetypeWeights: { networker: 2, caregiver: 1 } },
      { position: 4, label_fr: "Sens", label_en: "Meaning", archetypeWeights: { spiritual_seeker: 2, visionary: 1 } },
    ],
  },
  {
    position: 27,
    type: "ranking",
    prompt_fr: "Classez ces sources d'énergie du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these energy sources from strongest (1) to weakest (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Le corps en mouvement", label_en: "Body in motion", archetypeWeights: { athlete: 2 } },
      { position: 2, label_fr: "L'idée qui éclate", label_en: "The idea that bursts", archetypeWeights: { visionary: 2, intellectual: 1 } },
      { position: 3, label_fr: "L'autre qui s'éveille", label_en: "Another awakening", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 4, label_fr: "L'œuvre qui prend forme", label_en: "The work taking form", archetypeWeights: { artist: 2 } },
    ],
  },

  // ---- Short text (qualitative, no scoring weight) ----
  {
    position: 28,
    type: "short_text",
    prompt_fr: "En une phrase : qu'est-ce qui vous appelle en ce moment ?",
    prompt_en: "In one sentence: what is calling you right now?",
    isRequired: false,
    meta: { maxLength: 280 },
  },
  {
    position: 29,
    type: "short_text",
    prompt_fr: "Quel est, selon vous, votre plus grand point aveugle ?",
    prompt_en: "What is, in your view, your biggest blind spot?",
    isRequired: false,
    meta: { maxLength: 280 },
  },
  {
    position: 30,
    type: "short_text",
    prompt_fr: "Quelle pratique aimeriez-vous installer dans les 30 jours ?",
    prompt_en: "Which practice would you like to install in the next 30 days?",
    isRequired: false,
    meta: { maxLength: 280 },
  },
];
