import type { QuestionSeed } from "./types";

/**
 * 30 questions covering the 12 archetypes and 7 dimensions.
 * Mix of single_choice (archetype scoring), likert_scale (dimensions/shadow),
 * multiple_choice, ranking and short_text.
 */
export const QUESTIONS: QuestionSeed[] = [
  // ---- Single choice (archetype) ----
  {
    position: 1,
    type: "single_choice",
    prompt_fr: "Quand un projet démarre, qu'est-ce qui vous vient en premier ?",
    prompt_en: "When a project starts, what comes to you first?",
    options: [
      { position: 1, label_fr: "La vision globale et le futur souhaité", label_en: "The big picture and the desired future", archetypeWeights: { magician: 3, sovereign: 1 } },
      { position: 2, label_fr: "Les détails à comprendre et structurer", label_en: "The details to understand and structure", archetypeWeights: { sage: 3, explorer: 1 } },
      { position: 3, label_fr: "Les personnes à embarquer", label_en: "The people to bring along", archetypeWeights: { lover: 2, caregiver: 2 } },
      { position: 4, label_fr: "L'action concrète à lancer maintenant", label_en: "The concrete action to launch now", archetypeWeights: { warrior: 2, rebel: 2 } },
    ],
  },
  {
    position: 2,
    type: "single_choice",
    prompt_fr: "Face à une injustice, votre réflexe est de…",
    prompt_en: "Facing an injustice, your reflex is to…",
    options: [
      { position: 1, label_fr: "Prendre la parole publiquement", archetypeWeights: { caregiver: 3, rebel: 1 }, label_en: "Speak up publicly" },
      { position: 2, label_fr: "Soigner ceux qui sont touchés", archetypeWeights: { caregiver: 2, healer: 2 }, label_en: "Care for those impacted" },
      { position: 3, label_fr: "Analyser le système pour le réformer", archetypeWeights: { sage: 2, sovereign: 2 }, label_en: "Analyze the system to reform it" },
      { position: 4, label_fr: "Créer une œuvre qui en témoigne", archetypeWeights: { creator: 3 }, label_en: "Create a work that bears witness" },
    ],
  },
  {
    position: 3,
    type: "single_choice",
    prompt_fr: "Votre énergie déborde quand vous…",
    prompt_en: "Your energy overflows when you…",
    options: [
      { position: 1, label_fr: "Dépassez une limite physique", archetypeWeights: { warrior: 3 }, label_en: "Push past a physical limit" },
      { position: 2, label_fr: "Connectez deux personnes brillantes", archetypeWeights: { lover: 3 }, label_en: "Connect two brilliant people" },
      { position: 3, label_fr: "Apprenez quelque chose de neuf", archetypeWeights: { explorer: 3, sage: 1 }, label_en: "Learn something new" },
      { position: 4, label_fr: "Touchez le sacré ou l'invisible", archetypeWeights: { mystic: 3 }, label_en: "Touch the sacred or invisible" },
    ],
  },
  {
    position: 4,
    type: "single_choice",
    prompt_fr: "On vous reconnaît surtout pour…",
    prompt_en: "You are mostly recognized for…",
    options: [
      { position: 1, label_fr: "Votre clarté et votre autorité", archetypeWeights: { sovereign: 3 }, label_en: "Your clarity and authority" },
      { position: 2, label_fr: "Votre capacité à réparer / soigner", archetypeWeights: { healer: 3, caregiver: 1 }, label_en: "Your ability to repair / care" },
      { position: 3, label_fr: "Votre regard décalé / disruptif", archetypeWeights: { rebel: 3, creator: 1 }, label_en: "Your disruptive perspective" },
      { position: 4, label_fr: "Votre vision long terme", archetypeWeights: { magician: 3 }, label_en: "Your long-term vision" },
    ],
  },
  {
    position: 5,
    type: "single_choice",
    prompt_fr: "Quand vous êtes au mieux, vous…",
    prompt_en: "At your best, you…",
    options: [
      { position: 1, label_fr: "Décidez vite et juste", archetypeWeights: { sovereign: 2, warrior: 1 }, label_en: "Decide fast and right" },
      { position: 2, label_fr: "Créez quelque chose de neuf", archetypeWeights: { creator: 2, magician: 1 }, label_en: "Create something new" },
      { position: 3, label_fr: "Soutenez quelqu'un en croissance", archetypeWeights: { caregiver: 2, healer: 1 }, label_en: "Support someone growing" },
      { position: 4, label_fr: "Comprenez ce que d'autres ne voient pas", archetypeWeights: { sage: 2, mystic: 1 }, label_en: "See what others miss" },
    ],
  },
  {
    position: 6,
    type: "single_choice",
    prompt_fr: "Sous stress, vous avez tendance à…",
    prompt_en: "Under stress you tend to…",
    options: [
      { position: 1, label_fr: "Prendre le contrôle de tout", archetypeWeights: { sovereign: 1, warrior: 1 }, shadowWeights: { control: 2 }, label_en: "Take control of everything" },
      { position: 2, label_fr: "Vous retirer / disparaître", archetypeWeights: { mystic: 1 }, shadowWeights: { victim: 2 }, label_en: "Withdraw / disappear" },
      { position: 3, label_fr: "Dire oui à trop de choses", archetypeWeights: { caregiver: 1 }, shadowWeights: { prostitute: 2 }, label_en: "Say yes to too much" },
      { position: 4, label_fr: "Repousser la décision", archetypeWeights: { explorer: 1, sage: 1 }, shadowWeights: { saboteur: 2, victim: 1 }, label_en: "Postpone the decision" },
    ],
  },
  {
    position: 7,
    type: "single_choice",
    prompt_fr: "Votre plus grande peur est de…",
    prompt_en: "Your deepest fear is to…",
    options: [
      { position: 1, label_fr: "Ne pas avoir d'impact", archetypeWeights: { sovereign: 2, caregiver: 1 }, shadowWeights: { control: 1 }, label_en: "Have no impact" },
      { position: 2, label_fr: "Être abandonné·e", archetypeWeights: { caregiver: 2 }, shadowWeights: { prostitute: 1 }, label_en: "Be abandoned" },
      { position: 3, label_fr: "Être réduit·e au silence", archetypeWeights: { rebel: 2, caregiver: 1 }, label_en: "Be silenced" },
      { position: 4, label_fr: "Ne pas comprendre", archetypeWeights: { sage: 2, explorer: 1 }, shadowWeights: { victim: 1 }, label_en: "Not understand" },
    ],
  },
  {
    position: 8,
    type: "single_choice",
    prompt_fr: "Vous apprenez le mieux par…",
    prompt_en: "You learn best by…",
    dimension: "learning_style",
    options: [
      { position: 1, label_fr: "L'expérimentation directe", archetypeWeights: { warrior: 1, rebel: 1 }, value: 0.9, label_en: "Direct experimentation" },
      { position: 2, label_fr: "La lecture et la théorie", archetypeWeights: { sage: 2, explorer: 1 }, value: 0.7, label_en: "Reading and theory" },
      { position: 3, label_fr: "L'échange avec un mentor", archetypeWeights: { explorer: 2, lover: 1 }, value: 0.6, label_en: "Exchange with a mentor" },
      { position: 4, label_fr: "L'introspection silencieuse", archetypeWeights: { mystic: 2 }, value: 0.8, label_en: "Silent introspection" },
    ],
  },

  // ---- Multiple choice ----
  {
    position: 9,
    type: "multiple_choice",
    prompt_fr: "Quels environnements vous nourrissent ? (jusqu'à 3)",
    prompt_en: "Which environments feed you? (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "La nature silencieuse", archetypeWeights: { mystic: 2, healer: 1 }, label_en: "Silent nature" },
      { position: 2, label_fr: "Les espaces de création", archetypeWeights: { creator: 2 }, label_en: "Creative spaces" },
      { position: 3, label_fr: "Les salles de décision", archetypeWeights: { sovereign: 2, caregiver: 1 }, label_en: "Decision rooms" },
      { position: 4, label_fr: "Les terrains d'effort physique", archetypeWeights: { warrior: 2 }, label_en: "Physical training grounds" },
      { position: 5, label_fr: "Les communautés vibrantes", archetypeWeights: { lover: 2, caregiver: 1 }, label_en: "Vibrant communities" },
      { position: 6, label_fr: "Les bibliothèques", archetypeWeights: { sage: 2, explorer: 1 }, label_en: "Libraries" },
    ],
  },
  {
    position: 10,
    type: "multiple_choice",
    prompt_fr: "Qu'est-ce qui vous fait perdre votre énergie ? (jusqu'à 3)",
    prompt_en: "What drains your energy? (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Les conflits non résolus", shadowWeights: { victim: 1 }, archetypeWeights: { caregiver: 1 }, label_en: "Unresolved conflicts" },
      { position: 2, label_fr: "Les réunions sans décision", shadowWeights: { control: 1 }, archetypeWeights: { sovereign: 1 }, label_en: "Meetings without a decision" },
      { position: 3, label_fr: "Le bruit social superficiel", shadowWeights: { victim: 1 }, archetypeWeights: { sage: 1, mystic: 1 }, label_en: "Superficial social noise" },
      { position: 4, label_fr: "Les règles arbitraires", shadowWeights: { control: 1 }, archetypeWeights: { rebel: 2 }, label_en: "Arbitrary rules" },
      { position: 5, label_fr: "Devoir dire non", shadowWeights: { prostitute: 2 }, archetypeWeights: { caregiver: 1 }, label_en: "Having to say no" },
      { position: 6, label_fr: "Devoir performer", shadowWeights: { control: 2 }, archetypeWeights: { warrior: 1 }, label_en: "Having to perform" },
    ],
  },

  // ---- Likert (dimensions / shadow) ----
  {
    position: 11,
    type: "likert_scale",
    prompt_fr: "Je préfère apprendre seul·e plutôt qu'en groupe.",
    prompt_en: "I prefer learning alone rather than in a group.",
    dimension: "learning_style",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 12,
    type: "likert_scale",
    prompt_fr: "Mes meilleures décisions émergent dans la relation.",
    prompt_en: "My best decisions emerge in relationship.",
    dimension: "relational_style",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 13,
    type: "likert_scale",
    prompt_fr: "J'ai besoin d'intensité pour me sentir vivant·e.",
    prompt_en: "I need intensity to feel alive.",
    dimension: "activation_style",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 14,
    type: "likert_scale",
    prompt_fr: "Je sais redescendre rapidement après un pic de stress.",
    prompt_en: "I can come down quickly after a stress peak.",
    dimension: "regulation_need",
    helper_fr: "Réponse inversée : un score bas signifie un fort besoin de régulation.",
    helper_en: "Reverse-scored: a low answer means a high regulation need.",
    meta: { min: 1, max: 7, reverse: true },
    options: [
      { position: 1, value: 1, label_fr: "1", label_en: "1" },
      { position: 2, value: 6 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 5 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 3 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 2 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1 / 7, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 15,
    type: "likert_scale",
    prompt_fr: "Je fais confiance à mes intuitions, même sans preuve.",
    prompt_en: "I trust my intuitions even without proof.",
    dimension: "self_trust",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 16,
    type: "likert_scale",
    prompt_fr: "J'ai besoin d'exprimer ce que je vis, sinon je m'éteins.",
    prompt_en: "I need to express what I live, otherwise I dim.",
    dimension: "expression_need",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 17,
    type: "likert_scale",
    prompt_fr: "J'ai besoin d'un cadre clair pour donner le meilleur.",
    prompt_en: "I need a clear frame to give my best.",
    dimension: "structure_need",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", label_en: "6" },
      { position: 7, value: 1, label_fr: "7", label_en: "7" },
    ],
  },
  {
    position: 18,
    type: "likert_scale",
    prompt_fr: "J'ai du mal à déléguer ce qui compte vraiment.",
    prompt_en: "I struggle to delegate what really matters.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { control: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { control: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { control: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { control: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { control: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { control: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { control: 4 }, label_en: "7" },
    ],
  },
  {
    position: 19,
    type: "likert_scale",
    prompt_fr: "Je dis oui même quand mon corps dit non.",
    prompt_en: "I say yes even when my body says no.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { prostitute: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { prostitute: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { prostitute: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { prostitute: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { prostitute: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { prostitute: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { prostitute: 3 }, label_en: "7" },
    ],
  },
  {
    position: 20,
    type: "likert_scale",
    prompt_fr: "Quand c'est trop, je disparais socialement.",
    prompt_en: "When it's too much, I disappear socially.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { victim: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { victim: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { victim: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { victim: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { victim: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { victim: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { victim: 3 }, label_en: "7" },
    ],
  },
  {
    position: 21,
    type: "likert_scale",
    prompt_fr: "Je doute de mes décisions même quand elles sont bonnes.",
    prompt_en: "I doubt my decisions even when they are good.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { victim: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { victim: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { victim: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { victim: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { victim: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { victim: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { victim: 3 }, label_en: "7" },
    ],
  },
  {
    position: 22,
    type: "likert_scale",
    prompt_fr: "Tant que ce n'est pas parfait, je ne livre pas.",
    prompt_en: "Until it's perfect, I don't ship.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { control: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { control: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { control: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { control: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { control: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { control: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { control: 3 }, label_en: "7" },
    ],
  },
  {
    position: 23,
    type: "likert_scale",
    prompt_fr: "Je remets à plus tard ce qui me fait peur.",
    prompt_en: "I postpone what scares me.",
    meta: { min: 1, max: 7 },
    options: [
      { position: 1, value: 1 / 7, label_fr: "1", shadowWeights: { saboteur: 0 }, label_en: "1" },
      { position: 2, value: 2 / 7, label_fr: "2", shadowWeights: { saboteur: 0.5 }, label_en: "2" },
      { position: 3, value: 3 / 7, label_fr: "3", shadowWeights: { saboteur: 1 }, label_en: "3" },
      { position: 4, value: 4 / 7, label_fr: "4", shadowWeights: { saboteur: 1 }, label_en: "4" },
      { position: 5, value: 5 / 7, label_fr: "5", shadowWeights: { saboteur: 2 }, label_en: "5" },
      { position: 6, value: 6 / 7, label_fr: "6", shadowWeights: { saboteur: 2 }, label_en: "6" },
      { position: 7, value: 1, label_fr: "7", shadowWeights: { saboteur: 3 }, label_en: "7" },
    ],
  },

  // ---- Single choice (more archetype coverage) ----
  {
    position: 24,
    type: "single_choice",
    prompt_fr: "Le matin, ce qui vous met en route, c'est…",
    prompt_en: "In the morning, what gets you going is…",
    options: [
      { position: 1, label_fr: "Une intention claire", archetypeWeights: { magician: 2, sovereign: 1 }, label_en: "A clear intention" },
      { position: 2, label_fr: "Un rituel corporel", archetypeWeights: { warrior: 2, healer: 1 }, label_en: "A bodily ritual" },
      { position: 3, label_fr: "Une question ouverte", archetypeWeights: { sage: 2, explorer: 2 }, label_en: "An open question" },
      { position: 4, label_fr: "Un moment de silence", archetypeWeights: { mystic: 2 }, label_en: "A moment of silence" },
    ],
  },
  {
    position: 25,
    type: "single_choice",
    prompt_fr: "Quand vous coachez quelqu'un, votre force est…",
    prompt_en: "When you coach someone, your strength is…",
    options: [
      { position: 1, label_fr: "Voir leur potentiel inexploré", archetypeWeights: { magician: 2, healer: 1 }, label_en: "See their untapped potential" },
      { position: 2, label_fr: "Structurer un plan d'action", archetypeWeights: { sovereign: 2, sage: 1 }, label_en: "Structure an action plan" },
      { position: 3, label_fr: "Créer un espace sûr", archetypeWeights: { caregiver: 2, healer: 2 }, label_en: "Create a safe space" },
      { position: 4, label_fr: "Les confronter avec amour", archetypeWeights: { rebel: 2, caregiver: 1 }, label_en: "Confront them with love" },
    ],
  },

  // ---- Ranking ----
  {
    position: 26,
    type: "ranking",
    prompt_fr: "Classez ces moteurs internes du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these inner drivers from strongest (1) to weakest (4).",
    helper_fr: "Glissez pour réordonner.",
    helper_en: "Drag to reorder.",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Impact", label_en: "Impact", archetypeWeights: { sovereign: 2, caregiver: 1 } },
      { position: 2, label_fr: "Liberté", label_en: "Freedom", archetypeWeights: { rebel: 2, creator: 1 } },
      { position: 3, label_fr: "Lien", label_en: "Connection", archetypeWeights: { lover: 2, caregiver: 1 } },
      { position: 4, label_fr: "Sens", label_en: "Meaning", archetypeWeights: { mystic: 2, magician: 1 } },
    ],
  },
  {
    position: 27,
    type: "ranking",
    prompt_fr: "Classez ces sources d'énergie du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these energy sources from strongest (1) to weakest (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Le corps en mouvement", label_en: "Body in motion", archetypeWeights: { warrior: 2 } },
      { position: 2, label_fr: "L'idée qui éclate", label_en: "The idea that bursts", archetypeWeights: { magician: 2, sage: 1 } },
      { position: 3, label_fr: "L'autre qui s'éveille", label_en: "Another awakening", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 4, label_fr: "L'œuvre qui prend forme", label_en: "The work taking form", archetypeWeights: { creator: 2 } },
    ],
  },

  // ---- Short text (qualitative, no scoring weight) ----
  {
    position: 28,
    type: "short_text",
    prompt_fr: "En une phrase : qu'est-ce qui vous appelle en ce moment ?",
    prompt_en: "In one sentence: what is calling you right now?",
    isRequired: false,
    meta: { maxLength: 280 },
  },
  {
    position: 29,
    type: "short_text",
    prompt_fr: "Quel est, selon vous, votre plus grand point aveugle ?",
    prompt_en: "What is, in your view, your biggest blind spot?",
    isRequired: false,
    meta: { maxLength: 280 },
  },
  {
    position: 30,
    type: "short_text",
    prompt_fr: "Quelle pratique aimeriez-vous installer dans les 30 jours ?",
    prompt_en: "Which practice would you like to install in the next 30 days?",
    isRequired: false,
    meta: { maxLength: 280 },
  },

  /* ======================================================================== */
  /* CORE RENFORCEMENT (positions 31-33) — couverture archétypes              */
  /* ======================================================================== */
  {
    position: 31,
    type: "single_choice",
    prompt_fr: "Quand vous prenez la parole en public, vous le faites surtout pour…",
    prompt_en: "When you speak publicly, you mostly do it to…",
    options: [
      { position: 1, label_fr: "Défendre une cause ou une personne", label_en: "Defend a cause or a person", archetypeWeights: { caregiver: 3, rebel: 1 } },
      { position: 2, label_fr: "Connecter des mondes différents", label_en: "Connect different worlds", archetypeWeights: { lover: 3, magician: 1 } },
      { position: 3, label_fr: "Partager une création originale", label_en: "Share an original creation", archetypeWeights: { creator: 3 } },
      { position: 4, label_fr: "Transmettre un savoir précis", label_en: "Pass on precise knowledge", archetypeWeights: { sage: 2, explorer: 2 } },
    ],
  },
  {
    position: 32,
    type: "single_choice",
    prompt_fr: "Dans un groupe nouveau, vous êtes naturellement la personne qui…",
    prompt_en: "In a new group, you're naturally the person who…",
    options: [
      { position: 1, label_fr: "Tisse les liens entre les autres", label_en: "Weaves links between others", archetypeWeights: { lover: 3, caregiver: 1 } },
      { position: 2, label_fr: "Pose la question qui dérange", label_en: "Asks the disruptive question", archetypeWeights: { rebel: 2, caregiver: 2 } },
      { position: 3, label_fr: "Observe et capte l'ambiance", label_en: "Observes and captures the mood", archetypeWeights: { creator: 2, healer: 1, mystic: 1 } },
      { position: 4, label_fr: "Met de l'ordre et un cadre", label_en: "Brings order and a frame", archetypeWeights: { sovereign: 2, sage: 1 } },
    ],
  },
  {
    position: 33,
    type: "multiple_choice",
    prompt_fr: "Quels rôles assumez-vous le plus souvent ? (jusqu'à 3)",
    prompt_en: "Which roles do you take on most often? (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Porte-voix d'une cause", label_en: "Voice of a cause", archetypeWeights: { caregiver: 2 } },
      { position: 2, label_fr: "Créateur·rice d'œuvres", label_en: "Creator of works", archetypeWeights: { creator: 2 } },
      { position: 3, label_fr: "Pont entre les gens", label_en: "Bridge between people", archetypeWeights: { lover: 2 } },
      { position: 4, label_fr: "Décideur·euse final·e", label_en: "Final decision-maker", archetypeWeights: { sovereign: 2 } },
      { position: 5, label_fr: "Gardien·ne d'un savoir", label_en: "Keeper of knowledge", archetypeWeights: { sage: 2, explorer: 1 } },
      { position: 6, label_fr: "Soigneur·euse / réparateur·rice", label_en: "Healer / repairer", archetypeWeights: { healer: 2, caregiver: 1 } },
    ],
  },

  /* ======================================================================== */
  /* APPENDICE (positions 34-100) — Approfondissement optionnel               */
  /* ======================================================================== */

  // ---- 34-53 : 20 single_choice (couverture des 12 archétypes) ----
  {
    position: 34, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand vous lisez un article qui vous heurte, vous…",
    prompt_en: "When you read an article that offends you, you…",
    options: [
      { position: 1, label_fr: "Le partagez avec un commentaire engagé", label_en: "Share it with a committed comment", archetypeWeights: { caregiver: 3 } },
      { position: 2, label_fr: "Cherchez les sources contradictoires", label_en: "Look for contradicting sources", archetypeWeights: { sage: 3, explorer: 1 } },
      { position: 3, label_fr: "Le mettez en image, en mot, en son", label_en: "Turn it into image, word, sound", archetypeWeights: { creator: 3 } },
      { position: 4, label_fr: "Le laissez décanter en silence", label_en: "Let it settle in silence", archetypeWeights: { mystic: 2, healer: 1 } },
    ],
  },
  {
    position: 35, type: "single_choice", isAppendix: true,
    prompt_fr: "Une décision difficile à prendre, vous la travaillez…",
    prompt_en: "A hard decision, you work it through…",
    options: [
      { position: 1, label_fr: "Avec un tableau et des critères", label_en: "With a table and criteria", archetypeWeights: { sage: 3, sovereign: 1 } },
      { position: 2, label_fr: "En marchant, en bougeant", label_en: "Walking, moving", archetypeWeights: { warrior: 3 } },
      { position: 3, label_fr: "En appelant trois personnes de confiance", label_en: "Calling three trusted people", archetypeWeights: { lover: 2, caregiver: 1 } },
      { position: 4, label_fr: "En méditant ou en rêvant dessus", label_en: "Meditating or dreaming on it", archetypeWeights: { mystic: 3 } },
    ],
  },
  {
    position: 36, type: "single_choice", isAppendix: true,
    prompt_fr: "Un compliment qui vous touche le plus, c'est…",
    prompt_en: "The compliment that touches you most is…",
    options: [
      { position: 1, label_fr: "« Tu m'as ouvert les yeux »", label_en: "\"You opened my eyes\"", archetypeWeights: { magician: 3, caregiver: 1 } },
      { position: 2, label_fr: "« Avec toi je me sens en sécurité »", label_en: "\"With you I feel safe\"", archetypeWeights: { caregiver: 3, healer: 1 } },
      { position: 3, label_fr: "« Tu m'as fait avancer »", label_en: "\"You made me move forward\"", archetypeWeights: { sovereign: 2, warrior: 2 } },
      { position: 4, label_fr: "« Ce que tu as créé est unique »", label_en: "\"What you created is unique\"", archetypeWeights: { creator: 3 } },
    ],
  },
  {
    position: 37, type: "single_choice", isAppendix: true,
    prompt_fr: "Votre bibliothèque idéale contient surtout…",
    prompt_en: "Your ideal library mostly holds…",
    options: [
      { position: 1, label_fr: "Des essais et de la philosophie", label_en: "Essays and philosophy", archetypeWeights: { sage: 3, mystic: 1 } },
      { position: 2, label_fr: "Des biographies de bâtisseurs", label_en: "Biographies of builders", archetypeWeights: { sovereign: 2, magician: 2 } },
      { position: 3, label_fr: "De la poésie et des romans", label_en: "Poetry and novels", archetypeWeights: { creator: 3, healer: 1 } },
      { position: 4, label_fr: "Des manuels pratiques", label_en: "Practical manuals", archetypeWeights: { explorer: 3, warrior: 1 } },
    ],
  },
  {
    position: 38, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand vous êtes blessé·e émotionnellement, vous…",
    prompt_en: "When emotionally hurt, you…",
    options: [
      { position: 1, label_fr: "Vous isolez pour reprendre souffle", label_en: "Withdraw to catch your breath", archetypeWeights: { mystic: 2, healer: 1 }, shadowWeights: { victim: 2 } },
      { position: 2, label_fr: "Cherchez un·e proche pour parler", label_en: "Reach for someone to talk to", archetypeWeights: { lover: 2, caregiver: 1 } },
      { position: 3, label_fr: "Transformez la blessure en action", label_en: "Turn the hurt into action", archetypeWeights: { warrior: 2, caregiver: 2 } },
      { position: 4, label_fr: "L'écrivez ou la mettez en forme", label_en: "Write it or shape it", archetypeWeights: { creator: 3 } },
    ],
  },
  {
    position: 39, type: "single_choice", isAppendix: true,
    prompt_fr: "Le pouvoir, pour vous, sert avant tout à…",
    prompt_en: "Power, for you, mainly serves to…",
    options: [
      { position: 1, label_fr: "Protéger les plus fragiles", label_en: "Protect the most fragile", archetypeWeights: { caregiver: 4 } },
      { position: 2, label_fr: "Construire une vision long terme", label_en: "Build a long-term vision", archetypeWeights: { sovereign: 2, magician: 2 } },
      { position: 3, label_fr: "Briser des règles injustes", label_en: "Break unjust rules", archetypeWeights: { rebel: 3 } },
      { position: 4, label_fr: "Tisser des alliances durables", label_en: "Weave lasting alliances", archetypeWeights: { lover: 3 } },
    ],
  },
  {
    position: 40, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand un·e ami·e traverse une crise, vous…",
    prompt_en: "When a friend goes through a crisis, you…",
    options: [
      { position: 1, label_fr: "L'écoutez sans juger pendant des heures", label_en: "Listen without judging for hours", archetypeWeights: { healer: 3, caregiver: 1 } },
      { position: 2, label_fr: "L'aidez à structurer un plan", label_en: "Help them build a plan", archetypeWeights: { sovereign: 2, sage: 1 } },
      { position: 3, label_fr: "Le/la connectez à la bonne personne", label_en: "Connect them to the right person", archetypeWeights: { lover: 3 } },
      { position: 4, label_fr: "L'emmenez bouger / changer d'air", label_en: "Take them to move / get away", archetypeWeights: { warrior: 2, rebel: 1 } },
    ],
  },
  {
    position: 41, type: "single_choice", isAppendix: true,
    prompt_fr: "Votre rapport à l'argent ressemble à…",
    prompt_en: "Your relationship with money looks like…",
    options: [
      { position: 1, label_fr: "Un outil au service d'une vision", label_en: "A tool serving a vision", archetypeWeights: { magician: 2, sovereign: 2 } },
      { position: 2, label_fr: "Un sujet inconfortable à éviter", label_en: "An uncomfortable topic to avoid", archetypeWeights: { creator: 1, mystic: 1 }, shadowWeights: { saboteur: 2 } },
      { position: 3, label_fr: "Une preuve d'autonomie", label_en: "Proof of autonomy", archetypeWeights: { rebel: 2, warrior: 1 } },
      { position: 4, label_fr: "Un moyen de prendre soin des miens", label_en: "A way to care for my people", archetypeWeights: { caregiver: 3 } },
    ],
  },
  {
    position: 42, type: "single_choice", isAppendix: true,
    prompt_fr: "Une journée parfaite commence par…",
    prompt_en: "A perfect day starts with…",
    options: [
      { position: 1, label_fr: "Une pratique corporelle exigeante", label_en: "A demanding bodily practice", archetypeWeights: { warrior: 3 } },
      { position: 2, label_fr: "Un temps de prière ou méditation", label_en: "A time of prayer or meditation", archetypeWeights: { mystic: 3 } },
      { position: 3, label_fr: "Une lecture nourrissante", label_en: "A nourishing read", archetypeWeights: { sage: 2, explorer: 2 } },
      { position: 4, label_fr: "Un échange profond avec quelqu'un", label_en: "A deep exchange with someone", archetypeWeights: { lover: 2, caregiver: 1 } },
    ],
  },
  {
    position: 43, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand vous voyez une règle absurde, vous…",
    prompt_en: "When you see an absurd rule, you…",
    options: [
      { position: 1, label_fr: "La contournez immédiatement", label_en: "Bypass it right away", archetypeWeights: { rebel: 3 } },
      { position: 2, label_fr: "Tentez de la réformer dans le système", label_en: "Try to reform it from inside", archetypeWeights: { caregiver: 2, sovereign: 2 } },
      { position: 3, label_fr: "L'utilisez pour la transformer en œuvre", label_en: "Turn it into a creative work", archetypeWeights: { creator: 2 } },
      { position: 4, label_fr: "L'analysez avant d'agir", label_en: "Analyze before acting", archetypeWeights: { sage: 3 } },
    ],
  },
  {
    position: 44, type: "single_choice", isAppendix: true,
    prompt_fr: "Votre plus grande joie au travail vient de…",
    prompt_en: "Your greatest work joy comes from…",
    options: [
      { position: 1, label_fr: "Voir grandir les personnes que je guide", label_en: "Seeing people I guide grow", archetypeWeights: { caregiver: 2, healer: 2 } },
      { position: 2, label_fr: "Créer quelque chose qui n'existait pas", label_en: "Creating something new", archetypeWeights: { creator: 2, magician: 2 } },
      { position: 3, label_fr: "Atteindre un objectif difficile", label_en: "Reaching a hard goal", archetypeWeights: { warrior: 2, sovereign: 1 } },
      { position: 4, label_fr: "Comprendre ce que personne ne voyait", label_en: "Understanding what no one saw", archetypeWeights: { sage: 3 } },
    ],
  },
  {
    position: 45, type: "single_choice", isAppendix: true,
    prompt_fr: "Face à un·e expert·e reconnu·e, votre posture est…",
    prompt_en: "Facing a recognized expert, your posture is…",
    options: [
      { position: 1, label_fr: "Apprendre tout ce que je peux", label_en: "Learn everything I can", archetypeWeights: { explorer: 3, sage: 1 } },
      { position: 2, label_fr: "Challenger ses certitudes", label_en: "Challenge their certainties", archetypeWeights: { rebel: 2, caregiver: 1 } },
      { position: 3, label_fr: "Chercher la connexion humaine", label_en: "Look for human connection", archetypeWeights: { lover: 2, caregiver: 1 } },
      { position: 4, label_fr: "Évaluer si je veux travailler avec", label_en: "Assess if I want to work with them", archetypeWeights: { sovereign: 2 } },
    ],
  },
  {
    position: 46, type: "single_choice", isAppendix: true,
    prompt_fr: "Le silence prolongé, pour vous, c'est…",
    prompt_en: "Long silence, for you, is…",
    options: [
      { position: 1, label_fr: "Un espace sacré nécessaire", label_en: "A necessary sacred space", archetypeWeights: { mystic: 3, healer: 1 } },
      { position: 2, label_fr: "Un terrain fertile pour la création", label_en: "Fertile ground for creation", archetypeWeights: { creator: 2, sage: 1 } },
      { position: 3, label_fr: "Un moment difficile à habiter", label_en: "A hard moment to inhabit", archetypeWeights: { lover: 1, warrior: 1 }, shadowWeights: { saboteur: 1 } },
      { position: 4, label_fr: "Une marque de respect mutuel", label_en: "A mark of mutual respect", archetypeWeights: { caregiver: 2 } },
    ],
  },
  {
    position: 47, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand vous échouez, votre première réaction est…",
    prompt_en: "When you fail, your first reaction is…",
    options: [
      { position: 1, label_fr: "Analyser ce qui n'a pas marché", label_en: "Analyze what didn't work", archetypeWeights: { sage: 2, explorer: 2 } },
      { position: 2, label_fr: "Recommencer immédiatement", label_en: "Start again immediately", archetypeWeights: { warrior: 3, rebel: 1 } },
      { position: 3, label_fr: "Vous en vouloir longtemps", label_en: "Blame yourself for a long time", archetypeWeights: { caregiver: 1 }, shadowWeights: { victim: 2, control: 1 } },
      { position: 4, label_fr: "Chercher le sens caché", label_en: "Look for the hidden meaning", archetypeWeights: { mystic: 2, healer: 1 } },
    ],
  },
  {
    position: 48, type: "single_choice", isAppendix: true,
    prompt_fr: "Une équipe idéale ressemble à…",
    prompt_en: "An ideal team looks like…",
    options: [
      { position: 1, label_fr: "Un cercle d'experts complémentaires", label_en: "A circle of complementary experts", archetypeWeights: { sage: 2, sovereign: 2 } },
      { position: 2, label_fr: "Un commando agile", label_en: "An agile commando", archetypeWeights: { warrior: 2, rebel: 2 } },
      { position: 3, label_fr: "Une famille soudée", label_en: "A close-knit family", archetypeWeights: { caregiver: 3, lover: 1 } },
      { position: 4, label_fr: "Un atelier de créateurs", label_en: "A workshop of creators", archetypeWeights: { creator: 3, magician: 1 } },
    ],
  },
  {
    position: 49, type: "single_choice", isAppendix: true,
    prompt_fr: "Ce qui vous fait vraiment honte, c'est…",
    prompt_en: "What truly shames you is…",
    options: [
      { position: 1, label_fr: "Avoir trahi mes valeurs", label_en: "Betraying my values", archetypeWeights: { caregiver: 2, mystic: 1 } },
      { position: 2, label_fr: "Avoir blessé sans le vouloir", label_en: "Hurting without meaning to", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 3, label_fr: "Avoir produit un travail médiocre", label_en: "Producing mediocre work", archetypeWeights: { creator: 1, warrior: 1 }, shadowWeights: { control: 2 } },
      { position: 4, label_fr: "Avoir manqué de courage", label_en: "Lacking courage", archetypeWeights: { rebel: 2, sovereign: 1 } },
    ],
  },
  {
    position: 50, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand vous gagnez, vous voulez avant tout…",
    prompt_en: "When you win, you mostly want to…",
    options: [
      { position: 1, label_fr: "Le partager avec votre tribu", label_en: "Share it with your tribe", archetypeWeights: { lover: 3, caregiver: 1 } },
      { position: 2, label_fr: "Viser le défi suivant", label_en: "Aim for the next challenge", archetypeWeights: { warrior: 3, sovereign: 1 } },
      { position: 3, label_fr: "Honorer ce qui vous a porté·e", label_en: "Honor what carried you", archetypeWeights: { mystic: 2, healer: 1 } },
      { position: 4, label_fr: "Tirer la leçon pour mieux comprendre", label_en: "Extract the lesson", archetypeWeights: { sage: 2, explorer: 2 } },
    ],
  },
  {
    position: 51, type: "single_choice", isAppendix: true,
    prompt_fr: "Une réunion qui vous remplit d'énergie est celle où…",
    prompt_en: "A meeting that fills you with energy is one where…",
    options: [
      { position: 1, label_fr: "Une décision claire est prise", label_en: "A clear decision is made", archetypeWeights: { sovereign: 3, warrior: 1 } },
      { position: 2, label_fr: "Une idée nouvelle émerge", label_en: "A new idea emerges", archetypeWeights: { magician: 2, creator: 2 } },
      { position: 3, label_fr: "Les gens se disent vraiment les choses", label_en: "People truly tell each other the truth", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 4, label_fr: "Un savoir collectif se construit", label_en: "Collective knowledge is built", archetypeWeights: { sage: 2, explorer: 1 } },
    ],
  },
  {
    position: 52, type: "single_choice", isAppendix: true,
    prompt_fr: "Quand on vous tend un micro, votre première impulsion est…",
    prompt_en: "When handed a microphone, your first impulse is…",
    options: [
      { position: 1, label_fr: "Saisir l'occasion de défendre une idée", label_en: "Seize the chance to defend an idea", archetypeWeights: { caregiver: 3, rebel: 1 } },
      { position: 2, label_fr: "Donner une vision inspirante", label_en: "Give an inspiring vision", archetypeWeights: { magician: 3, sovereign: 1 } },
      { position: 3, label_fr: "Raconter une histoire personnelle", label_en: "Tell a personal story", archetypeWeights: { creator: 3, healer: 1 } },
      { position: 4, label_fr: "Refuser poliment ou abréger", label_en: "Politely decline or cut short", archetypeWeights: { mystic: 1, sage: 1 }, shadowWeights: { victim: 2 } },
    ],
  },
  {
    position: 53, type: "single_choice", isAppendix: true,
    prompt_fr: "Votre signature unique au monde, c'est…",
    prompt_en: "Your unique signature in the world is…",
    options: [
      { position: 1, label_fr: "Mon œil esthétique et créatif", label_en: "My aesthetic, creative eye", archetypeWeights: { creator: 3 } },
      { position: 2, label_fr: "Ma capacité à fédérer", label_en: "My ability to bring people together", archetypeWeights: { lover: 2, sovereign: 2 } },
      { position: 3, label_fr: "Mon endurance hors-norme", label_en: "My uncommon endurance", archetypeWeights: { warrior: 3 } },
      { position: 4, label_fr: "Mon flair pour le sens caché", label_en: "My nose for hidden meaning", archetypeWeights: { mystic: 2, sage: 2 } },
    ],
  },

  // ---- 54-73 : 20 likert (raffinement shadow + dimensions) ----
  {
    position: 54, type: "likert_scale", isAppendix: true,
    prompt_fr: "J'apprends mieux quand je peux enseigner ce que j'apprends.",
    prompt_en: "I learn better when I can teach what I learn.",
    dimension: "learning_style",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 55, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je préfère travailler en duo plutôt que seul·e ou en groupe.",
    prompt_en: "I prefer working in duos rather than alone or in groups.",
    dimension: "relational_style",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 56, type: "likert_scale", isAppendix: true,
    prompt_fr: "J'ai besoin de longues plages de calme pour récupérer.",
    prompt_en: "I need long stretches of calm to recover.",
    dimension: "regulation_need",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 57, type: "likert_scale", isAppendix: true,
    prompt_fr: "Quand mon intuition contredit la donnée, je suis l'intuition.",
    prompt_en: "When my intuition contradicts the data, I follow intuition.",
    dimension: "self_trust",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 58, type: "likert_scale", isAppendix: true,
    prompt_fr: "Sans création artistique, je me sens diminué·e.",
    prompt_en: "Without artistic creation, I feel diminished.",
    dimension: "expression_need",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 59, type: "likert_scale", isAppendix: true,
    prompt_fr: "Sans plan écrit, j'ai du mal à démarrer.",
    prompt_en: "Without a written plan, I struggle to start.",
    dimension: "structure_need",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 60, type: "likert_scale", isAppendix: true,
    prompt_fr: "L'intensité physique me régule plus que le repos.",
    prompt_en: "Physical intensity regulates me more than rest.",
    dimension: "activation_style",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 61, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je vérifie mon travail plusieurs fois avant de le livrer.",
    prompt_en: "I check my work several times before delivering.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { control: Math.max(0, (n-3)*0.75) } })),
  },
  {
    position: 62, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je préfère tout faire moi-même pour être sûr·e.",
    prompt_en: "I'd rather do everything myself to be sure.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { control: Math.max(0, (n-3)*0.75) } })),
  },
  {
    position: 63, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je détecte vite quand l'autre n'est pas content de moi.",
    prompt_en: "I quickly sense when others are unhappy with me.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { prostitute: Math.max(0, (n-3)*0.75) } })),
  },
  {
    position: 64, type: "likert_scale", isAppendix: true,
    prompt_fr: "Quand on me critique, je rumine longtemps.",
    prompt_en: "When criticized, I ruminate for a long time.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { victim: Math.max(0, (n-3)*0.75) } })),
  },
  {
    position: 65, type: "likert_scale", isAppendix: true,
    prompt_fr: "Quand un sujet me coûte, je le repousse au lendemain.",
    prompt_en: "When a topic costs me, I push it to tomorrow.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { saboteur: Math.max(0, (n-3)*0.75) } })),
  },
  {
    position: 66, type: "likert_scale", isAppendix: true,
    prompt_fr: "Quand le groupe est trop bruyant, je m'éclipse mentalement.",
    prompt_en: "When the group is too loud, I check out mentally.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { victim: Math.max(0, (n-3)*0.75) } })),
  },
  {
    position: 67, type: "likert_scale", isAppendix: true,
    prompt_fr: "J'ai besoin de poser une intention claire avant d'agir.",
    prompt_en: "I need to set a clear intention before acting.",
    dimension: "structure_need",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 68, type: "likert_scale", isAppendix: true,
    prompt_fr: "Mes émotions montent fort et redescendent lentement.",
    prompt_en: "My emotions rise high and come down slowly.",
    dimension: "regulation_need",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 69, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je sais déléguer même les sujets à fort enjeu.",
    prompt_en: "I can delegate even high-stakes topics.",
    helper_fr: "Réponse inversée : un score bas indique un fort enjeu de contrôle.",
    helper_en: "Reverse-scored: a low answer means a strong control issue.",
    meta: { min: 1, max: 7, reverse: true },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===1?1:(8-n)/7, label_fr: String(n), label_en: String(n), shadowWeights: { control: Math.max(0, (4-n)*0.5) } })),
  },
  {
    position: 70, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je dis ma vérité même quand elle dérange.",
    prompt_en: "I speak my truth even when it disturbs.",
    helper_fr: "Réponse inversée : un score bas indique du people pleasing.",
    helper_en: "Reverse-scored: a low answer indicates people pleasing.",
    meta: { min: 1, max: 7, reverse: true },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===1?1:(8-n)/7, label_fr: String(n), label_en: String(n), shadowWeights: { prostitute: Math.max(0, (4-n)*0.5) } })),
  },
  {
    position: 71, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je commence souvent un projet sans le finir.",
    prompt_en: "I often start a project without finishing it.",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n), shadowWeights: { saboteur: Math.max(0, (n-4)*0.6) } })),
  },
  {
    position: 72, type: "likert_scale", isAppendix: true,
    prompt_fr: "L'échange à plusieurs me stimule plus que la solitude.",
    prompt_en: "Group exchange stimulates me more than solitude.",
    dimension: "relational_style",
    meta: { min: 1, max: 7 },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===7?1:n/7, label_fr: String(n), label_en: String(n) })),
  },
  {
    position: 73, type: "likert_scale", isAppendix: true,
    prompt_fr: "Je suis capable de revenir au calme en moins de 10 minutes.",
    prompt_en: "I can return to calm in less than 10 minutes.",
    dimension: "regulation_need",
    helper_fr: "Réponse inversée : un score bas signifie un fort besoin de régulation.",
    helper_en: "Reverse-scored: a low answer means a high regulation need.",
    meta: { min: 1, max: 7, reverse: true },
    options: [1,2,3,4,5,6,7].map((n) => ({ position: n, value: n===1?1:(8-n)/7, label_fr: String(n), label_en: String(n) })),
  },

  // ---- 74-88 : 15 multiple_choice (comportements, valeurs, contextes) ----
  {
    position: 74, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos sources d'inspiration majeures sont… (jusqu'à 3)",
    prompt_en: "Your major sources of inspiration are… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Les traditions spirituelles", label_en: "Spiritual traditions", archetypeWeights: { mystic: 2, healer: 1 } },
      { position: 2, label_fr: "Les biographies de leaders", label_en: "Leader biographies", archetypeWeights: { sovereign: 2, magician: 1 } },
      { position: 3, label_fr: "L'art et la littérature", label_en: "Art and literature", archetypeWeights: { creator: 2 } },
      { position: 4, label_fr: "La science et la recherche", label_en: "Science and research", archetypeWeights: { sage: 2, explorer: 1 } },
      { position: 5, label_fr: "Les mouvements sociaux", label_en: "Social movements", archetypeWeights: { caregiver: 2, rebel: 1 } },
      { position: 6, label_fr: "Les performances physiques", label_en: "Physical feats", archetypeWeights: { warrior: 2 } },
    ],
  },
  {
    position: 75, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Ce qui rend un projet irrésistible pour vous… (jusqu'à 3)",
    prompt_en: "What makes a project irresistible to you… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Une cause juste à servir", label_en: "A just cause to serve", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 2, label_fr: "Une vision audacieuse à incarner", label_en: "A bold vision to embody", archetypeWeights: { magician: 2, sovereign: 1 } },
      { position: 3, label_fr: "Une équipe humaine forte", label_en: "A strong human team", archetypeWeights: { lover: 2, caregiver: 1 } },
      { position: 4, label_fr: "Un défi technique complexe", label_en: "A complex technical challenge", archetypeWeights: { sage: 2, explorer: 1 } },
      { position: 5, label_fr: "Un terrain de liberté", label_en: "A field of freedom", archetypeWeights: { rebel: 2, creator: 1 } },
      { position: 6, label_fr: "Une exigence physique", label_en: "A physical demand", archetypeWeights: { warrior: 2 } },
    ],
  },
  {
    position: 76, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Quelles valeurs guident vos décisions ? (jusqu'à 3)",
    prompt_en: "Which values guide your decisions? (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Justice", label_en: "Justice", archetypeWeights: { caregiver: 2 } },
      { position: 2, label_fr: "Liberté", label_en: "Freedom", archetypeWeights: { rebel: 2 } },
      { position: 3, label_fr: "Excellence", label_en: "Excellence", archetypeWeights: { warrior: 1, sovereign: 1 }, shadowWeights: { control: 1 } },
      { position: 4, label_fr: "Bienveillance", label_en: "Kindness", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 5, label_fr: "Vérité", label_en: "Truth", archetypeWeights: { sage: 2, caregiver: 1 } },
      { position: 6, label_fr: "Sens", label_en: "Meaning", archetypeWeights: { mystic: 2, magician: 1 } },
    ],
  },
  {
    position: 77, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos zones de croissance prioritaires sont… (jusqu'à 3)",
    prompt_en: "Your priority growth zones are… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Apprendre à dire non", label_en: "Learning to say no", shadowWeights: { prostitute: 2 } },
      { position: 2, label_fr: "Lâcher le contrôle", label_en: "Letting go of control", shadowWeights: { control: 2 } },
      { position: 3, label_fr: "Oser livrer imparfait", label_en: "Daring to ship imperfect", shadowWeights: { control: 2 } },
      { position: 4, label_fr: "Affronter ce que j'évite", label_en: "Facing what I avoid", shadowWeights: { saboteur: 2 } },
      { position: 5, label_fr: "Faire confiance à mon jugement", label_en: "Trusting my own judgment", shadowWeights: { victim: 2 } },
      { position: 6, label_fr: "Rester en lien sous stress", label_en: "Staying connected under stress", shadowWeights: { victim: 2 } },
    ],
  },
  {
    position: 78, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos rituels de régénération préférés sont… (jusqu'à 3)",
    prompt_en: "Your favorite regeneration rituals are… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Sport intense", label_en: "Intense sport", archetypeWeights: { warrior: 2 } },
      { position: 2, label_fr: "Méditation / prière", label_en: "Meditation / prayer", archetypeWeights: { mystic: 2 } },
      { position: 3, label_fr: "Création artistique", label_en: "Artistic creation", archetypeWeights: { creator: 2 } },
      { position: 4, label_fr: "Nature et marche longue", label_en: "Nature and long walks", archetypeWeights: { healer: 2, mystic: 1 } },
      { position: 5, label_fr: "Lecture profonde", label_en: "Deep reading", archetypeWeights: { sage: 2, explorer: 1 } },
      { position: 6, label_fr: "Repas avec mes proches", label_en: "Meals with loved ones", archetypeWeights: { caregiver: 2, lover: 1 } },
    ],
  },
  {
    position: 79, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Les contextes où vous donnez votre meilleur… (jusqu'à 3)",
    prompt_en: "Contexts where you're at your best… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "En crise, sous pression", label_en: "In crisis, under pressure", archetypeWeights: { sovereign: 2, warrior: 1 } },
      { position: 2, label_fr: "Dans la phase de design", label_en: "In the design phase", archetypeWeights: { magician: 2, creator: 1 } },
      { position: 3, label_fr: "En tête-à-tête profond", label_en: "In deep one-on-one", archetypeWeights: { healer: 2, caregiver: 1 } },
      { position: 4, label_fr: "Devant un public", label_en: "Facing an audience", archetypeWeights: { caregiver: 2, creator: 1 } },
      { position: 5, label_fr: "En recherche solitaire", label_en: "In solitary research", archetypeWeights: { sage: 2, mystic: 1 } },
      { position: 6, label_fr: "Dans la mise en réseau", label_en: "In networking", archetypeWeights: { lover: 2 } },
    ],
  },
  {
    position: 80, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Ce qui vous met vraiment en colère… (jusqu'à 3)",
    prompt_en: "What truly angers you… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "L'injustice systémique", label_en: "Systemic injustice", archetypeWeights: { caregiver: 2, rebel: 1 } },
      { position: 2, label_fr: "La médiocrité acceptée", label_en: "Accepted mediocrity", archetypeWeights: { sovereign: 1, warrior: 1 }, shadowWeights: { control: 1 } },
      { position: 3, label_fr: "Le mensonge subtil", label_en: "Subtle lying", archetypeWeights: { sage: 1, caregiver: 2 } },
      { position: 4, label_fr: "L'irrespect des plus fragiles", label_en: "Disrespect for the fragile", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 5, label_fr: "L'autorité abusive", label_en: "Abusive authority", archetypeWeights: { rebel: 3 } },
      { position: 6, label_fr: "La fermeture spirituelle", label_en: "Spiritual closure", archetypeWeights: { mystic: 2 } },
    ],
  },
  {
    position: 81, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos modes de prise de décision préférés… (jusqu'à 2)",
    prompt_en: "Your preferred decision-making modes… (up to 2)",
    meta: { maxSelect: 2 },
    options: [
      { position: 1, label_fr: "Analyse rationnelle", label_en: "Rational analysis", archetypeWeights: { sage: 2 } },
      { position: 2, label_fr: "Intuition viscérale", label_en: "Gut intuition", archetypeWeights: { warrior: 1, mystic: 2 } },
      { position: 3, label_fr: "Consultation collective", label_en: "Collective consultation", archetypeWeights: { lover: 2, caregiver: 1 } },
      { position: 4, label_fr: "Décision rapide assumée", label_en: "Fast assumed decision", archetypeWeights: { sovereign: 2, warrior: 1 } },
    ],
  },
  {
    position: 82, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos modes de communication les plus puissants… (jusqu'à 3)",
    prompt_en: "Your most powerful communication modes… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "L'écrit posé et structuré", label_en: "Written, structured", archetypeWeights: { sage: 2 } },
      { position: 2, label_fr: "Le face-à-face intime", label_en: "Intimate face-to-face", archetypeWeights: { healer: 2, caregiver: 1 } },
      { position: 3, label_fr: "Le discours public", label_en: "Public speech", archetypeWeights: { caregiver: 2, sovereign: 1 } },
      { position: 4, label_fr: "L'œuvre symbolique", label_en: "Symbolic work", archetypeWeights: { creator: 2, mystic: 1 } },
      { position: 5, label_fr: "Le geste, l'exemple", label_en: "Action, leading by example", archetypeWeights: { warrior: 2, rebel: 1 } },
      { position: 6, label_fr: "Le dialogue ouvert", label_en: "Open dialogue", archetypeWeights: { lover: 2, explorer: 1 } },
    ],
  },
  {
    position: 83, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Sous forte pression, vous risquez de… (jusqu'à 3)",
    prompt_en: "Under high pressure, you risk… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Tout micro-manager", label_en: "Micro-managing everything", shadowWeights: { control: 3 } },
      { position: 2, label_fr: "Dire oui à tout", label_en: "Saying yes to everything", shadowWeights: { prostitute: 2 } },
      { position: 3, label_fr: "Disparaître émotionnellement", label_en: "Emotionally disappearing", shadowWeights: { victim: 2 } },
      { position: 4, label_fr: "Reporter sans cesse", label_en: "Endlessly postponing", shadowWeights: { saboteur: 2 } },
      { position: 5, label_fr: "Douter de chaque décision", label_en: "Doubting every decision", shadowWeights: { victim: 2 } },
      { position: 6, label_fr: "Réécrire dix fois la même chose", label_en: "Rewriting the same thing ten times", shadowWeights: { control: 2 } },
    ],
  },
  {
    position: 84, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Ce qui vous met en mouvement le matin… (jusqu'à 2)",
    prompt_en: "What gets you moving in the morning… (up to 2)",
    meta: { maxSelect: 2 },
    options: [
      { position: 1, label_fr: "Un objectif chiffré à atteindre", label_en: "A measurable goal", archetypeWeights: { warrior: 2, sovereign: 1 } },
      { position: 2, label_fr: "Une création à faire éclore", label_en: "A creation to unfold", archetypeWeights: { creator: 2, magician: 1 } },
      { position: 3, label_fr: "Une personne à soutenir", label_en: "A person to support", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 4, label_fr: "Une question à éclaircir", label_en: "A question to clarify", archetypeWeights: { sage: 2, explorer: 1 } },
    ],
  },
  {
    position: 85, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Ce qui vous coûte le plus dans le leadership… (jusqu'à 3)",
    prompt_en: "What costs you most in leadership… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Trancher quand l'équipe est divisée", label_en: "Deciding when the team is split", archetypeWeights: { sovereign: 1, caregiver: 1 }, shadowWeights: { victim: 1 } },
      { position: 2, label_fr: "Recadrer quelqu'un que j'aime", label_en: "Reframing someone I love", archetypeWeights: { caregiver: 1 }, shadowWeights: { prostitute: 2 } },
      { position: 3, label_fr: "Déléguer ce qui m'importe", label_en: "Delegating what matters to me", shadowWeights: { control: 2 } },
      { position: 4, label_fr: "Tenir le cap sur la durée", label_en: "Staying the course over time", archetypeWeights: { warrior: 1, sovereign: 1 } },
      { position: 5, label_fr: "Communiquer une mauvaise nouvelle", label_en: "Sharing bad news", shadowWeights: { saboteur: 2 } },
      { position: 6, label_fr: "Recevoir une critique frontale", label_en: "Receiving frontal criticism", shadowWeights: { victim: 2 } },
    ],
  },
  {
    position: 86, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos talents reconnus par les autres… (jusqu'à 3)",
    prompt_en: "Talents others recognize in you… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Vision long terme", label_en: "Long-term vision", archetypeWeights: { magician: 2, sovereign: 1 } },
      { position: 2, label_fr: "Capacité d'analyse", label_en: "Analytical depth", archetypeWeights: { sage: 2 } },
      { position: 3, label_fr: "Présence apaisante", label_en: "Soothing presence", archetypeWeights: { healer: 2, caregiver: 1 } },
      { position: 4, label_fr: "Sens artistique", label_en: "Artistic sense", archetypeWeights: { creator: 2 } },
      { position: 5, label_fr: "Mise en lien", label_en: "Connection-making", archetypeWeights: { lover: 2 } },
      { position: 6, label_fr: "Endurance / discipline", label_en: "Endurance / discipline", archetypeWeights: { warrior: 2 } },
    ],
  },
  {
    position: 87, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Vos rituels d'apprentissage favoris… (jusqu'à 2)",
    prompt_en: "Your favorite learning rituals… (up to 2)",
    meta: { maxSelect: 2 },
    options: [
      { position: 1, label_fr: "Pratique répétée jusqu'à maîtrise", label_en: "Practice until mastery", archetypeWeights: { warrior: 2, explorer: 1 } },
      { position: 2, label_fr: "Étude approfondie d'un texte", label_en: "Deep study of a text", archetypeWeights: { sage: 2, explorer: 1 } },
      { position: 3, label_fr: "Conversation avec un mentor", label_en: "Conversation with a mentor", archetypeWeights: { explorer: 2, lover: 1 } },
      { position: 4, label_fr: "Expérience immersive sur le terrain", label_en: "Immersive field experience", archetypeWeights: { rebel: 1, warrior: 1, explorer: 1 } },
    ],
  },
  {
    position: 88, type: "multiple_choice", isAppendix: true,
    prompt_fr: "Les qualités d'un partenaire idéal pour vous… (jusqu'à 3)",
    prompt_en: "Ideal partner qualities for you… (up to 3)",
    meta: { maxSelect: 3 },
    options: [
      { position: 1, label_fr: "Loyauté absolue", label_en: "Absolute loyalty", archetypeWeights: { caregiver: 2, sovereign: 1 } },
      { position: 2, label_fr: "Intelligence vive", label_en: "Sharp intelligence", archetypeWeights: { sage: 2 } },
      { position: 3, label_fr: "Sensibilité artistique", label_en: "Artistic sensibility", archetypeWeights: { creator: 2, healer: 1 } },
      { position: 4, label_fr: "Engagement éthique", label_en: "Ethical commitment", archetypeWeights: { caregiver: 2, mystic: 1 } },
      { position: 5, label_fr: "Énergie de vie", label_en: "Life energy", archetypeWeights: { warrior: 2, lover: 1 } },
      { position: 6, label_fr: "Profondeur intérieure", label_en: "Inner depth", archetypeWeights: { mystic: 2, healer: 1 } },
    ],
  },

  // ---- 89-95 : 7 ranking (moteurs, valeurs, priorités) ----
  {
    position: 89, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces sources de sécurité du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these sources of safety from strongest (1) to weakest (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Cadre clair et structures", label_en: "Clear frame and structures", archetypeWeights: { sovereign: 2, sage: 1 } },
      { position: 2, label_fr: "Liens humains profonds", label_en: "Deep human bonds", archetypeWeights: { caregiver: 2, lover: 1 } },
      { position: 3, label_fr: "Maîtrise corporelle", label_en: "Bodily mastery", archetypeWeights: { warrior: 2 } },
      { position: 4, label_fr: "Connexion spirituelle", label_en: "Spiritual connection", archetypeWeights: { mystic: 2 } },
    ],
  },
  {
    position: 90, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces priorités de vie du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these life priorities from strongest (1) to weakest (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Laisser une trace", label_en: "Leave a legacy", archetypeWeights: { sovereign: 2, magician: 1 } },
      { position: 2, label_fr: "Vivre pleinement chaque jour", label_en: "Live each day fully", archetypeWeights: { warrior: 1, creator: 2 } },
      { position: 3, label_fr: "Servir plus grand que soi", label_en: "Serve something greater", archetypeWeights: { caregiver: 2, mystic: 1 } },
      { position: 4, label_fr: "Apprendre toujours plus", label_en: "Keep learning more", archetypeWeights: { explorer: 2, sage: 1 } },
    ],
  },
  {
    position: 91, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces formes de reconnaissance du plus puissant (1) au moins (4).",
    prompt_en: "Rank these forms of recognition from most (1) to least powerful (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Reconnaissance publique", label_en: "Public recognition", archetypeWeights: { sovereign: 2, caregiver: 1 } },
      { position: 2, label_fr: "Gratitude intime d'un proche", label_en: "Intimate gratitude from a loved one", archetypeWeights: { caregiver: 2, healer: 1 } },
      { position: 3, label_fr: "Validation par les pairs experts", label_en: "Validation from expert peers", archetypeWeights: { sage: 2, explorer: 1 } },
      { position: 4, label_fr: "Sentiment intérieur d'avoir bien fait", label_en: "Inner sense of having done well", archetypeWeights: { mystic: 2 } },
    ],
  },
  {
    position: 92, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces zones de risque ombre du plus dangereux pour vous (1) au moins (4).",
    prompt_en: "Rank these shadow risk zones from most dangerous to you (1) to least (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Vouloir tout contrôler", label_en: "Wanting to control everything", shadowWeights: { control: 2 } },
      { position: 2, label_fr: "Plaire à tout prix", label_en: "Pleasing at any cost", shadowWeights: { prostitute: 2 } },
      { position: 3, label_fr: "Rechercher la perfection", label_en: "Seeking perfection", shadowWeights: { control: 2 } },
      { position: 4, label_fr: "Disparaître / se replier", label_en: "Disappearing / withdrawing", shadowWeights: { victim: 2 } },
    ],
  },
  {
    position: 93, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces tensions internes du plus fort (1) au plus faible (4).",
    prompt_en: "Rank these inner tensions from strongest (1) to weakest (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Action vs réflexion", label_en: "Action vs reflection", archetypeWeights: { warrior: 1, sage: 1 } },
      { position: 2, label_fr: "Solitude vs liens", label_en: "Solitude vs ties", archetypeWeights: { mystic: 1, lover: 1 } },
      { position: 3, label_fr: "Soumission vs rébellion", label_en: "Submission vs rebellion", archetypeWeights: { rebel: 1, sovereign: 1 } },
      { position: 4, label_fr: "Donner vs recevoir", label_en: "Giving vs receiving", archetypeWeights: { caregiver: 1, healer: 1 } },
    ],
  },
  {
    position: 94, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces postures de leadership du plus naturel (1) au moins (4).",
    prompt_en: "Rank these leadership postures from most natural (1) to least (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Le ou la stratège qui décide", label_en: "The strategist who decides", archetypeWeights: { sovereign: 3 } },
      { position: 2, label_fr: "Le ou la mentor qui élève", label_en: "The mentor who lifts up", archetypeWeights: { caregiver: 2, healer: 2 } },
      { position: 3, label_fr: "L'éclaireur·euse qui ouvre la voie", label_en: "The pathfinder", archetypeWeights: { magician: 2, rebel: 1 } },
      { position: 4, label_fr: "Le ou la pédagogue qui transmet", label_en: "The teacher who transmits", archetypeWeights: { sage: 2, explorer: 1 } },
    ],
  },
  {
    position: 95, type: "ranking", isAppendix: true,
    prompt_fr: "Classez ces formes de récupération du plus efficace (1) au moins (4).",
    prompt_en: "Rank these recovery forms from most (1) to least effective (4).",
    meta: { count: 4 },
    options: [
      { position: 1, label_fr: "Sport et corps", label_en: "Sport and body", archetypeWeights: { warrior: 2 } },
      { position: 2, label_fr: "Solitude et silence", label_en: "Solitude and silence", archetypeWeights: { mystic: 2 } },
      { position: 3, label_fr: "Création et expression", label_en: "Creation and expression", archetypeWeights: { creator: 2 } },
      { position: 4, label_fr: "Lien et conversation", label_en: "Connection and conversation", archetypeWeights: { lover: 2, caregiver: 1 } },
    ],
  },

  // ---- 96-100 : 5 short_text optionnels (mix profil profond / action) ----
  {
    position: 96, type: "short_text", isAppendix: true, isRequired: false,
    prompt_fr: "Quelle est la peur la plus profonde que vous n'avez jamais nommée ?",
    prompt_en: "What is the deepest fear you've never named?",
    meta: { maxLength: 280 },
  },
  {
    position: 97, type: "short_text", isAppendix: true, isRequired: false,
    prompt_fr: "Quel succès êtes-vous le plus fier·e d'avoir gardé secret ?",
    prompt_en: "What success are you most proud to have kept secret?",
    meta: { maxLength: 280 },
  },
  {
    position: 98, type: "short_text", isAppendix: true, isRequired: false,
    prompt_fr: "Quel héritage voulez-vous laisser dans cinq ans ?",
    prompt_en: "What legacy do you want to leave in five years?",
    meta: { maxLength: 280 },
  },
  {
    position: 99, type: "short_text", isAppendix: true, isRequired: false,
    prompt_fr: "Quelle décision difficile devez-vous prendre dans les 90 jours ?",
    prompt_en: "What hard decision must you take in the next 90 days?",
    meta: { maxLength: 280 },
  },
  {
    position: 100, type: "short_text", isAppendix: true, isRequired: false,
    prompt_fr: "Quelle leçon récente avez-vous apprise sur vous-même ?",
    prompt_en: "What recent lesson have you learned about yourself?",
    meta: { maxLength: 280 },
  },
];

/* -------------------------------------------------------------------------- */
/* Filtered exports                                                           */
/* -------------------------------------------------------------------------- */

/** Core questions only (positions 1-33) — required to generate the radar + results. */
export const CORE_QUESTIONS: QuestionSeed[] = QUESTIONS.filter((q) => !q.isAppendix);

/** Appendix questions (positions 34-100) — optional deepening, answered from profile. */
export const APPENDIX_QUESTIONS: QuestionSeed[] = QUESTIONS.filter((q) => q.isAppendix);

