import type { ToolSeed } from "./types";

/**
 * 25 recommended tools across meditation, breathwork, journal_prompt, micro_practice.
 * `widgetKey` maps to existing Toolbox widget when applicable so we reuse what's there
 * (Breathwork, BodyScan, Affirmations, Gratitude, Visualization, Intention,
 *  StopProtocol, FocusIntrospectif, JournalPrompt) and create new ones only when needed.
 */
export const TOOLS: ToolSeed[] = [
  // --- breathwork (existing widget) ---
  {
    key: "coherent_breathing_5min",
    type: "breathwork",
    widgetKey: "BreathworkWidget",
    title_fr: "Respiration cohérente 5/5",
    title_en: "Coherent breathing 5/5",
    duration_fr: "5 min",
    duration_en: "5 min",
    archetypes: ["queen", "athlete", "advocate"],
    dimensions: ["regulation_need", "activation_style"],
    shadows: ["control"],
    rationaleHint_fr: "régule le système nerveux avant les décisions à fort enjeu",
    rationaleHint_en: "regulates the nervous system before high-stakes decisions",
  },
  {
    key: "box_breathing_4x4",
    type: "breathwork",
    widgetKey: "BreathworkWidget",
    title_fr: "Respiration carrée 4-4-4-4",
    title_en: "Box breathing 4-4-4-4",
    duration_fr: "4 min",
    duration_en: "4 min",
    archetypes: ["athlete", "queen", "intellectual"],
    shadows: ["control", "perfectionism"],
    rationaleHint_fr: "stabilise le focus avant une exécution précise",
    rationaleHint_en: "stabilizes focus before precise execution",
  },
  {
    key: "physiological_sigh",
    type: "breathwork",
    widgetKey: "BreathworkWidget",
    title_fr: "Soupir physiologique",
    title_en: "Physiological sigh",
    duration_fr: "1 min",
    duration_en: "1 min",
    archetypes: ["caregiver", "healer", "rebel"],
    shadows: ["withdrawal", "people_pleasing"],
    rationaleHint_fr: "abaisse le stress en moins d'une minute",
    rationaleHint_en: "drops stress in under a minute",
  },

  // --- meditation ---
  {
    key: "body_scan_10min",
    type: "meditation",
    widgetKey: "BodyScanWidget",
    title_fr: "Body scan complet",
    title_en: "Full body scan",
    duration_fr: "10 min",
    duration_en: "10 min",
    archetypes: ["intellectual", "visionary", "spiritual_seeker"],
    dimensions: ["regulation_need"],
    shadows: ["withdrawal", "avoidance"],
    rationaleHint_fr: "réincarne la pensée et désactive la sur-mentalisation",
    rationaleHint_en: "re-embodies thought and reduces over-thinking",
  },
  {
    key: "loving_kindness",
    type: "meditation",
    title_fr: "Méditation de bienveillance",
    title_en: "Loving-kindness meditation",
    duration_fr: "12 min",
    duration_en: "12 min",
    archetypes: ["caregiver", "healer", "advocate"],
    shadows: ["self_doubt", "people_pleasing"],
    rationaleHint_fr: "rééquilibre le don de soi par l'amour de soi",
    rationaleHint_en: "rebalances giving with self-love",
  },
  {
    key: "open_awareness",
    type: "meditation",
    title_fr: "Attention ouverte",
    title_en: "Open awareness",
    duration_fr: "15 min",
    duration_en: "15 min",
    archetypes: ["spiritual_seeker", "visionary", "artist"],
    rationaleHint_fr: "élargit la perception au-delà du mental analytique",
    rationaleHint_en: "expands perception beyond analytical mind",
  },
  {
    key: "grounding_3min",
    type: "meditation",
    title_fr: "Ancrage 3 minutes",
    title_en: "3-minute grounding",
    duration_fr: "3 min",
    duration_en: "3 min",
    archetypes: ["rebel", "artist", "networker"],
    shadows: ["avoidance", "withdrawal"],
    rationaleHint_fr: "reconnecte au corps et au présent en moins de 3 minutes",
    rationaleHint_en: "reconnects to body and present in under 3 minutes",
  },
  {
    key: "visualization_future_self",
    type: "meditation",
    widgetKey: "VisualizationWidget",
    title_fr: "Visualisation : moi futur",
    title_en: "Visualization: future self",
    duration_fr: "8 min",
    duration_en: "8 min",
    archetypes: ["visionary", "queen", "athlete"],
    rationaleHint_fr: "ancre une trajectoire désirable dans le corps",
    rationaleHint_en: "anchors a desirable trajectory in the body",
  },

  // --- journal_prompt ---
  {
    key: "shadow_journal_control",
    type: "journal_prompt",
    widgetKey: "JournalPromptWidget",
    title_fr: "Journal d'ombre — contrôle",
    title_en: "Shadow journal — control",
    duration_fr: "10 min",
    duration_en: "10 min",
    archetypes: ["queen", "intellectual"],
    shadows: ["control", "perfectionism"],
    rationaleHint_fr: "explore là où le besoin de contrôle vous coupe du flux",
    rationaleHint_en: "explores where the need for control cuts you off from flow",
  },
  {
    key: "shadow_journal_pleasing",
    type: "journal_prompt",
    widgetKey: "JournalPromptWidget",
    title_fr: "Journal d'ombre — plaire à tout prix",
    title_en: "Shadow journal — people-pleasing",
    duration_fr: "10 min",
    duration_en: "10 min",
    archetypes: ["caregiver", "networker"],
    shadows: ["people_pleasing", "self_doubt"],
    rationaleHint_fr: "met en lumière les oui automatiques qui vous épuisent",
    rationaleHint_en: "surfaces automatic yes-es that exhaust you",
  },
  {
    key: "values_clarification",
    type: "journal_prompt",
    widgetKey: "JournalPromptWidget",
    title_fr: "Clarification de valeurs",
    title_en: "Values clarification",
    duration_fr: "15 min",
    duration_en: "15 min",
    archetypes: ["advocate", "queen", "visionary", "spiritual_seeker"],
    dimensions: ["self_trust", "structure_need"],
    rationaleHint_fr: "aligne les décisions du quotidien avec vos valeurs profondes",
    rationaleHint_en: "aligns daily decisions with your deep values",
  },
  {
    key: "creative_morning_pages",
    type: "journal_prompt",
    widgetKey: "JournalPromptWidget",
    title_fr: "Pages du matin",
    title_en: "Morning pages",
    duration_fr: "20 min",
    duration_en: "20 min",
    archetypes: ["artist", "visionary", "rebel"],
    dimensions: ["expression_need"],
    rationaleHint_fr: "vide l'esprit pour libérer la créativité du jour",
    rationaleHint_en: "empties the mind to free the day's creativity",
  },
  {
    key: "decision_log_prompt",
    type: "journal_prompt",
    widgetKey: "JournalPromptWidget",
    title_fr: "Journal de décision",
    title_en: "Decision journal",
    duration_fr: "8 min",
    duration_en: "8 min",
    archetypes: ["queen", "intellectual", "advocate"],
    dimensions: ["self_trust"],
    shadows: ["self_doubt"],
    rationaleHint_fr: "renforce la confiance décisionnelle par la traçabilité",
    rationaleHint_en: "builds decision confidence through traceability",
  },
  {
    key: "gratitude_3",
    type: "journal_prompt",
    widgetKey: "GratitudeWidget",
    title_fr: "Trois gratitudes",
    title_en: "Three gratitudes",
    duration_fr: "5 min",
    duration_en: "5 min",
    archetypes: ["caregiver", "healer", "spiritual_seeker"],
    rationaleHint_fr: "réoriente l'attention vers ce qui nourrit",
    rationaleHint_en: "reorients attention toward what nourishes",
  },
  {
    key: "rebel_inquiry",
    type: "journal_prompt",
    widgetKey: "JournalPromptWidget",
    title_fr: "Investigation du non",
    title_en: "Inquiry of the no",
    duration_fr: "10 min",
    duration_en: "10 min",
    archetypes: ["rebel"],
    shadows: ["control", "avoidance"],
    rationaleHint_fr: "discerne entre rébellion réactive et choix conscient",
    rationaleHint_en: "discerns reactive rebellion from conscious choice",
  },

  // --- micro_practice ---
  {
    key: "stop_protocol",
    type: "micro_practice",
    widgetKey: "StopProtocolWidget",
    title_fr: "Protocole STOP",
    title_en: "STOP protocol",
    duration_fr: "2 min",
    duration_en: "2 min",
    archetypes: ["athlete", "queen", "rebel", "advocate"],
    shadows: ["control", "perfectionism"],
    rationaleHint_fr: "introduit une pause consciente avant la réaction",
    rationaleHint_en: "inserts a conscious pause before reaction",
  },
  {
    key: "intention_setting",
    type: "micro_practice",
    widgetKey: "IntentionWidget",
    title_fr: "Intention du jour",
    title_en: "Daily intention",
    duration_fr: "3 min",
    duration_en: "3 min",
    archetypes: ["visionary", "queen", "spiritual_seeker", "advocate"],
    dimensions: ["structure_need", "self_trust"],
    rationaleHint_fr: "donne une direction claire à la journée",
    rationaleHint_en: "gives the day a clear direction",
  },
  {
    key: "affirmations_morning",
    type: "micro_practice",
    widgetKey: "AffirmationsWidget",
    title_fr: "Affirmations du matin",
    title_en: "Morning affirmations",
    duration_fr: "4 min",
    duration_en: "4 min",
    archetypes: ["caregiver", "student", "artist"],
    shadows: ["self_doubt"],
    rationaleHint_fr: "renforce une voix interne soutenante",
    rationaleHint_en: "strengthens a supportive inner voice",
  },
  {
    key: "focus_introspectif",
    type: "micro_practice",
    widgetKey: "FocusIntrospectifWidget",
    title_fr: "Focus introspectif",
    title_en: "Introspective focus",
    duration_fr: "6 min",
    duration_en: "6 min",
    archetypes: ["intellectual", "spiritual_seeker", "student"],
    dimensions: ["learning_style"],
    rationaleHint_fr: "structure une introspection courte et utile",
    rationaleHint_en: "structures a short and useful introspection",
  },
  {
    key: "movement_break",
    type: "micro_practice",
    title_fr: "Pause mouvement",
    title_en: "Movement break",
    duration_fr: "3 min",
    duration_en: "3 min",
    archetypes: ["athlete", "rebel", "networker"],
    dimensions: ["activation_style"],
    rationaleHint_fr: "décharge la tension par le corps",
    rationaleHint_en: "discharges tension through the body",
  },
  {
    key: "boundary_phrase",
    type: "micro_practice",
    title_fr: "Phrase-limite",
    title_en: "Boundary phrase",
    duration_fr: "2 min",
    duration_en: "2 min",
    archetypes: ["caregiver", "healer", "advocate"],
    shadows: ["people_pleasing"],
    rationaleHint_fr: "prépare un non clair et respectueux à l'avance",
    rationaleHint_en: "rehearses a clear and respectful no in advance",
  },
  {
    key: "single_task_block",
    type: "micro_practice",
    title_fr: "Bloc mono-tâche 25 min",
    title_en: "Single-task block 25 min",
    duration_fr: "25 min",
    duration_en: "25 min",
    archetypes: ["intellectual", "queen", "athlete"],
    dimensions: ["structure_need"],
    shadows: ["avoidance"],
    rationaleHint_fr: "protège une vraie plage d'exécution",
    rationaleHint_en: "protects a true execution window",
  },
  {
    key: "connection_call",
    type: "micro_practice",
    title_fr: "Appel de lien (10 min)",
    title_en: "Connection call (10 min)",
    duration_fr: "10 min",
    duration_en: "10 min",
    archetypes: ["networker", "caregiver", "advocate"],
    dimensions: ["relational_style"],
    rationaleHint_fr: "nourrit le réseau sans transactionnel",
    rationaleHint_en: "feeds the network without transactionality",
  },
  {
    key: "learning_loop",
    type: "micro_practice",
    title_fr: "Boucle d'apprentissage 1-3-1",
    title_en: "Learning loop 1-3-1",
    duration_fr: "10 min",
    duration_en: "10 min",
    archetypes: ["student", "intellectual", "visionary"],
    dimensions: ["learning_style"],
    rationaleHint_fr: "transforme la lecture en connaissance utilisable",
    rationaleHint_en: "turns reading into usable knowledge",
  },
  {
    key: "creative_constraint",
    type: "micro_practice",
    title_fr: "Contrainte créative",
    title_en: "Creative constraint",
    duration_fr: "15 min",
    duration_en: "15 min",
    archetypes: ["artist", "rebel", "visionary"],
    dimensions: ["expression_need"],
    shadows: ["perfectionism"],
    rationaleHint_fr: "débloque la création par la limite imposée",
    rationaleHint_en: "unlocks creation through imposed limits",
  },
];

export function getTool(key: string): ToolSeed {
  const t = TOOLS.find((x) => x.key === key);
  if (!t) throw new Error(`Unknown tool: ${key}`);
  return t;
}
