import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { archetypeMeta } from "./assessmentService";
import type { ArchetypeKey } from "../domain/types";

interface ExportArgs {
  isFR: boolean;
  firstName: string;
  submittedAt: Date;
  radarElement: HTMLElement | null;
  narrative: string;
  topScores: Array<{ archetype_key: string; normalized_score: number }>;
  dominantKey: ArchetypeKey | null;
  growthKey: ArchetypeKey | null;
}

function slugify(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export async function exportProfileToPdf({
  isFR,
  firstName,
  submittedAt,
  radarElement,
  narrative,
  topScores,
  dominantKey,
  growthKey,
}: ExportArgs): Promise<void> {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 14;
  let y = margin;

  // Header
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.setTextColor(20, 20, 30);
  pdf.text(isFR ? "Profil archétypal Aegis" : "Aegis archetypal profile", margin, y);
  y += 8;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(90, 90, 100);
  const dateStr = submittedAt.toLocaleDateString(isFR ? "fr-FR" : "en-US", {
    day: "numeric", month: "long", year: "numeric",
  });
  pdf.text(`${firstName} · ${dateStr}`, margin, y);
  y += 8;

  // Badges
  if (dominantKey || growthKey) {
    pdf.setFontSize(10);
    if (dominantKey) {
      const d = archetypeMeta(dominantKey);
      const label = `${isFR ? "Archétype dominant" : "Dominant archetype"}: ${d ? (isFR ? d.name_fr : d.name_en) : dominantKey}`;
      pdf.setTextColor(40, 40, 50);
      pdf.text(label, margin, y);
      y += 5;
    }
    if (growthKey) {
      const g = archetypeMeta(growthKey);
      const label = `${isFR ? "Archétype de croissance" : "Growth archetype"}: ${g ? (isFR ? g.name_fr : g.name_en) : growthKey}`;
      pdf.setTextColor(40, 40, 50);
      pdf.text(label, margin, y);
      y += 5;
    }
    y += 2;
  }

  // Radar snapshot
  if (radarElement) {
    try {
      const canvas = await html2canvas(radarElement, {
        backgroundColor: "#ffffff",
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const imgData = canvas.toDataURL("image/png");
      const maxImgW = pageW - margin * 2;
      const ratio = canvas.height / canvas.width;
      const imgW = maxImgW;
      const imgH = imgW * ratio;
      if (y + imgH > pageH - margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.addImage(imgData, "PNG", margin, y, imgW, Math.min(imgH, pageH - margin - y));
      y += Math.min(imgH, pageH - margin - y) + 6;
    } catch {
      // fail silently — text content still exports
    }
  }

  // Narrative
  if (narrative) {
    if (y > pageH - 50) { pdf.addPage(); y = margin; }
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(20, 20, 30);
    pdf.text(isFR ? "Ton récit archétypal" : "Your archetypal narrative", margin, y);
    y += 6;

    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(10);
    pdf.setTextColor(50, 50, 60);
    const lines = pdf.splitTextToSize(narrative, pageW - margin * 2);
    pdf.text(lines, margin, y);
    y += lines.length * 5 + 4;
  }

  // Top 5
  const top5 = [...topScores]
    .sort((a, b) => Number(b.normalized_score) - Number(a.normalized_score))
    .slice(0, 5);
  if (top5.length) {
    if (y > pageH - 50) { pdf.addPage(); y = margin; }
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(20, 20, 30);
    pdf.text(isFR ? "Top 5 archétypes" : "Top 5 archetypes", margin, y);
    y += 6;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(40, 40, 50);
    top5.forEach((row, i) => {
      const meta = archetypeMeta(row.archetype_key as ArchetypeKey);
      const name = meta ? (isFR ? meta.name_fr : meta.name_en) : row.archetype_key;
      const score = Number(row.normalized_score).toFixed(1);
      pdf.text(`${i + 1}. ${name} — ${score}%`, margin, y);
      y += 5;
    });
    y += 2;
  }

  // Footer
  const footerY = pageH - 8;
  pdf.setFont("helvetica", "italic");
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 130);
  const footer = isFR
    ? "Généré par Aegis — basé sur les archétypes de Caroline Myss"
    : "Generated by Aegis — based on Caroline Myss's archetypes";
  pdf.text(footer, pageW / 2, footerY, { align: "center" });

  // Filename
  const yyyy = submittedAt.getFullYear();
  const mm = String(submittedAt.getMonth() + 1).padStart(2, "0");
  const dd = String(submittedAt.getDate()).padStart(2, "0");
  const safeName = slugify(firstName || "profil") || "profil";
  pdf.save(`aegis-profile-${safeName}-${yyyy}-${mm}-${dd}.pdf`);
}
